<title>SRMS System | Module List</title>
<?php 
	$url_new = $this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'acl',
		'action'=>'add-acl',
	));
	$url = Application_Form_FrmMessage::getUrl("/rsvAcl/acl/edit-acl?id=");
?>

<div class="btn" align="right">
	<input  type="button" value="បន្ថែម​ថ្មី" label="បន្ថែម​ថ្មី" id="btadd" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $url_new; ?>';"/>
</div>
<form name="frmlist" action="" dojoType="dijit.form.Form" method="post">
	<table class="fullside">
		  <tr>
		  	<td>	  		
		  		<?php echo $this->list;?>
		  	</td>
		  	
		  </tr>		  
	</table>
</form>
