<title>3PC System | View Module</title>
<?php 
	$cancel_url=$this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'acl',
		'action'=>'index',
	));

?>

<div class="btn" align="right">
	<input  type="button" value="ត្រលប់​ក្រោយ" label="ត្រលប់​ក្រោយ" id="btadd" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $cancel_url; ?>';"/>
</div>

<table cellspacing="20" style="margin: 0 auto; width: 450px">
	<tr>
		<td>
			<fieldset>
				<legend><strong>Module/Controller/Action</strong></legend>
				<table cellspacing="20" width="100%">
					<tr>
						<td align="center" valign="top">
							<table>
								<tr>
									<td>Module</td>
									<td width="200px"><?php echo $this->acl_data['module'];?></td>
								</tr>
								<tr>
									<td>Contoller</td>
									<td width="200px"><?php echo $this->acl_data['controller'];?></td>
								</tr>
								<tr>
									<td>Action</td>
									<td width="200px"><?php echo $this->acl_data['action'];?></td>
								</tr>						
							</table>
						</td>							
					</tr>
				</table>	
			</fieldset>
		</td>			
	</tr>		
</table>	
	
<script type="text/javascript">
	dojo.require('dijit.form.Button');
</script>