<script type="text/javascript">
	dojo.require('dijit.form.Button');	
	dojo.require('dijit.form.ValidateTextBox');	
</script>
<?php 
	$url_submit =  $this->url(array('module'=>'backup','controller'=>'Index','action'=>'restore'));
?>
<form id="frm" name="frm"  action="<?php echo $url_submit; ?>" method="post" enctype="multipart/form-data">
	<table cellspacing="20" border="1">
		<tr>
			<td>Choose File (.sql)</td>
			<td><input type="file" name="fileToUpload" id="fileToUpload" dojoType="dijit.form.Button" label="Choose File" 
			iconClass="dijitIconFolderOpen" onchange="alert(2);" >
	 		</td>
		</tr>
		<tr>
			<td></td>
			<td><input type="submit" value="Restore Now" label="Restore Now" id="busyButton" dojoType="dijit.form.Button" 
				iconClass="dijitIconSave" /> </td>
		</tr>
	</table>
</form>
