<?php
$this->headTitle('Currency Smart | User change password page'); 
echo $this->headTitle();
?>

<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');	
</script>
<form action="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				if(dojo.byId('new_password').value != dojo.byId('new_con_password').value ){
					alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
					dojo.byId('new_password').value = '';
					dojo.byId('new_con_password').value = '';
					dijit.byId('new_password').focus();
					return false;
				}				
				return true;
			}

			return false;
	</script>
		
	<table cellspacing="20" style="margin: 0 auto; width: 480px">
		<tr>
			<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន  សំរាប់ ប្តូរ ពាក្យ​សំងាត់</strong></legend>
					<table cellspacing="20" width="100%">
						<tr>
							<td align="center" valign="top">
								<table width="100%">
									<tr>
										<td>ពាក្យ​​សំងាត់ កំពុង​ប្រើ​ប្រាស់</td>							
										<td>
											<input type="password" required="true" name="password" id="password" placeholder="ពាក្យ​​សំងាត់ កំពុង​ប្រើ​ប្រាស់" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​  ពាក្យ​​សំងាត់ កំពុង​ប្រើ​ប្រាស់!" style="width: 100%;"/>
										</td>
									</tr>
									<tr>
										<td>ពាក្យ​​សំងាត់ ថ្មី</td>							
										<td>
											<input type="password" required="true" name="new_password" id="new_password" placeholder="ពាក្យ​​សំងាត់ ថ្មី" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពាក្យ​​សំងាត់ ថ្មី!" style="width: 100%;"/>
										</td>
									</tr>
									<tr>
										<td>បញ្ជាក់ពាក្យ​​សំងាត់  ថ្មី</td>							
										<td>
											<input type="password" required="true" name="new_con_password" id="new_con_password" placeholder="បញ្ជាក់ពាក្យ​​សំងាត់  ថ្មី"
											regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ" 
											dojoType="dijit.form.ValidationTextBox"  missingMessage="អ្នក​ភ្លេច​បំពេញ​ បញ្ជាក់ ពាក្យ​​សំងាត់ ថ្មី!" style="width: 100%;"/>
										</td>
									</tr>																	
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>