<title>SRMS System | User Access Level</title>
<?php 
	header("Cache-Control: no-cache, must-revalidate");
	$url_user = $this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'user',
		'action'=>'index',
	));
	
	$url_user_type = $this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'user-type',
		'action'=>'index',
	));
	
	$url_user_acl = $this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'acl',
		'action'=>'index',
	));
	$url_user_access = $this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'user-access',
		'action'=>'index',
	));
?>
<script type="text/javascript">
<!--
	$(function(){
		// Tabs
		//$('#tabs').tabs();		
	});

	
//-->
</script>
<!-- 
<div id="tabs">
	<ul>
		<li><a href="<?php echo $url_user;?>">User Management</a></li>
		<li><a href="<?php echo $url_user_type;?>">User Type Management</a></li>
		<li><a href="<?php echo $url_user_acl;?>">Module Management</a></li>
		<li><a href="<?php echo $url_user_access;?>">Module Assignment</a></li>
	</ul>
</div>
 -->