<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS| WU REGESTER'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript">
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.Dialog");
	dojo.require("dojo.data.ItemFileWriteStore"); 

	var marjor_store  = getDataStorefromJSON('id','major_name', <?php print_r(Zend_Json::encode($this->marjorlist));?> );
	
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
</style>
<?php $register = $this->frm_register;?>

<form id='office_receipt' action="<?php echo $this->url(array('module'=>'transfer','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table  cellspacing="10" style="margin: 0 auto; width: 80%;" >
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("OFFICIAL_RECEIPT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD; padding:10px;" cellspacing="7" >
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("NEW_STUDENT");?></td>
							<td><?php echo $register->getElement('is_new');?>
								<?php echo $tr->translate("NEW_YEAR_ONE");?>
								<?php echo $register->getElement('is_year_one');?>
							</td>
							<td style="width: 160px"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td><?php echo $register->getElement('stu_id');?></td>
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DOB");?></td>
							<td>
								<input type="text" name="dob" id="dob" value="<?php echo date("Y-m-d")-20;?>" 
								dojoType="dijit.form.DateTextBox" required="true" missingMessage="<?php echo $tr->translate("​FORGET_POB!")?>" 
								 class='fullside' />
								
							<?php //echo $register->getElement('dob');?></td>
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><?php echo $register->getElement('phone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEGREE");?></td>
							<td><?php echo $register->getElement('degree');?></td>
							<td><?php echo $tr->translate("BATCH");?></td>
							<td><?php echo $register->getElement('batch');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEPARTMENT");?></td>
							<td><?php echo $register->getElement('dept');?></td>
							<td><?php echo $tr->translate("MAJOR_C");?></td>
							<td><?php echo $register->getElement('major');?></td>
						</tr>
						<tr>
							
							<td><?php echo $tr->translate("YEARTH");?></td>
							<td><?php echo $register->getElement('year');?></td>
							<td><?php echo $tr->translate("SESSION");?></td>
							<td><?php echo $register->getElement('session');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PAYMENT_TERM");?></td>
							<td><?php echo $register->getElement('payment_term');?></td>
							<td><?php echo $tr->translate("TUITION_FEE");?></td>
							<td><?php echo $register->getElement('fee');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("DISCOUND");?></td>
							<td><?php echo $register->getElement('discount');?></td>
							<td><?php echo $tr->translate("AMOUNT_PAID");?></td>
							<td><?php echo $register->getElement('payment_paid');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate('IN_WORDS');?></td>
							<td><?php echo $register->getElement('paid_kh');?></td>
							<td><?php echo $tr->translate("REMARK");?></td>
							<td><?php echo $register->getElement('remark');;?></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td colspan="2">
							<input type="button" value="Save" label="Save" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId('frm_add_tran').submit();"/>
								<input type="button" value="Save & Print" label="Save & Print" id="busyButton" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
function printSave(){		
	if(dijit.byId('office_receipt').validate()) {
		/*if(dijit.byId('recieve_money').get('value') < dijit.byId('total').get('value') || dijit.byId('return_money').get('value') < 0){
			alert('សូម​ពិនិត្រ ទឹក​ដែល​​ទទួល​បាន​ម្តង ​ទៀត..');
			dijit.byId('recieve_money').focus();
			return false;
		}*/
		//showDialog();		
		dojo.byId("lb_receipt_no").innerHTML = dijit.byId("reciept_no").value;
		//dojo.byId("lb_paydate").innerHTML = dijit.byId("pay_date").value;
		dojo.byId("lb_kh_stuname").innerHTML = dijit.byId("kh_name").value;
		dojo.byId("lb_en_stuname").innerHTML = dijit.byId("en_name").value;
		dojo.byId("lb_student_id").innerHTML = dijit.byId("stu_id").value;
		dojo.byId("lb_sex").innerHTML = dijit.byId('sex').attr('displayedValue');
		//dojo.byId("lb_dob").innerHTML = dijit.byId("dob").value;
		dojo.byId("lb_degree").innerHTML = dijit.byId('degree').attr('displayedValue');
		dojo.byId("lb_phone").innerHTML = dijit.byId("phone").value;
		dojo.byId("lb_major").innerHTML = dijit.byId('dept').attr('displayedValue');

		
		dojo.byId("lb_batch").innerHTML = dijit.byId("batch").value;
		dojo.byId("lb_year").innerHTML = dijit.byId("year").value;
		dojo.byId("lb_session").innerHTML = dijit.byId('session').attr('displayedValue');
		dojo.byId("lb_term").innerHTML = dijit.byId('payment_term').attr('displayedValue');
		dojo.byId("lb_fee").innerHTML = dijit.byId("fee").value;
		dojo.byId("lb_discound").innerHTML = dijit.byId("discount").value;
		dojo.byId("lb_amount_paid").innerHTML = dijit.byId("payment_paid").value;
		//dojo.byId("lb_in_khmer").innerHTML = dijit.byId("paid_kh").value;
		//dojo.byId("lb_byuser").innerHTML = dijit.byId("kh_name").value;
		dijit.byId("terms").show();	
	}
	
}
</script>
<div class="dijitHidden">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT");?>'" id="terms" >
		<div id="divPrint" style="width: 21cm; height: 14cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
			</style>	
			<table bgcolor="fef7e4" cellspacing="5" style="width: 21cm;height: 14cm; font-size:12pt; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px;">
					<tr height="50px">
						<td><img src="<?php echo $base_url.'/images/logo-letter.gif';?>" width="100%"/></td>
					   	<td align="center" colspan="2">	
				            <strong style="font:bold 20px 'Kh Muol';"><?php echo $keycode['reciept_kh'];?></strong><br/>
							<strong style="font-size: 20px;font-weight:bold"><?php echo $keycode['reciept_en'];?></strong><br/>
			            </td>
			            <td></td>
				   </tr>
				   <tr height="50px">
						<td>
							<div style="border:1px solid #e14109;font-size:8pt; width:170px;; padding:10px; text-align: center;">
			            		<label style=" color:#e14109;">ប្រាក់ដែលបង់រួចមិនអាចដកវិញបានទេ</label><br />
			            		<label style=" color:#e14109; text-align: center">Nonrefundable</label>
			            	</div></td>
					   	<td></td>
			            <td align="center" colspan="2">
			            	<div style="border:1px solid rgba(14, 0, 107, 1);font-size:large; width:160px; border-radius:10px; padding:10px;">
			            		Receipt N<sup>o</sup> : <label style=" color:#e14109;" id="lb_receipt_no"></label><br />
			            		Date : <?php echo date("d-M-Y");?>
			            	</div>
			            </td>
				   </tr>
					<tr>
						<td width="25%">នាម - គោត្តនាម</td>
						<td  width="25%">&nbsp; : <label id="lb_kh_stuname"></label></td>
						<td  width="25%">Full Name(First|Last):</td>
					   	<td  width="25%">&nbsp; : <label id="lb_en_stuname"></label></td>
				   </tr>
				   <tr>
						<td>ID N<sup>o</sup></td>
						<td>&nbsp; : <label id="lb_student_id"></label></td>
						<td>Sex</td>
					   	<td>&nbsp; : <label id="lb_sex"></label></td>
				   </tr>
				   <tr>
						<td>Date of Birth</td>
						<td>&nbsp; : <label id="lb_dob"></label></td>
						<td>Degree</td>
						<td>&nbsp; : <label id="lb_degree"></label></td>
				   </tr>
				    <tr>
						<td>Phone</td>
						<td>&nbsp; : <label id="lb_phone"></label></td>
						<td>Major</td>
						<td>&nbsp; : <label id="lb_major"></label></td>
				   </tr>
				   <tr>
						<td>Batch</td>
						<td>&nbsp; : <label id="lb_batch"></label></td>
						<td>Major</td>
						<td>&nbsp; : <label id="dkdk"></label></td>
				   </tr>
				    <tr>
						<td>Year</td>
						<td>&nbsp; : <label id="lb_year"></label></td>
						<td>Session</td>
						<td>&nbsp; : <label id="lb_session"></label></td>
				   </tr>
				   <tr>
						<td>Payment Term</td>
						<td>&nbsp; : <label id="lb_term"></label></td>
						<td>Tuition Fee</td>
						<td><strong>&nbsp; : $ <label id="lb_fee"></label></strong></td>
				   </tr>
				   <tr>
						<td>Discound</td>
						<td><strong>&nbsp; : $ <label id="lb_discound"></label></strong></td>
						<td>Amount Paid</td>
						<td><strong>&nbsp; : $ <label id="lb_amount_paid"></label></strong></td>
				   </tr>
				   <tr>
						<td>ឈ្មោះអ្នកទទូល :</td>
						<td>&nbsp; : <?php $session_user=new Zend_Session_Namespace('auth');
			        			$username = $session_user->first_name; echo $username;?></td>
						<td>Paid Date</td>
						<td>&nbsp; : 23/02/2014</td>
				   </tr>
				  <?php echo $this->footer;?>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
	</div>
</div>
<script>
var url_get = '<?php echo $this->url(array('module'=>'registrar','controller'=>'index','action'=>'get-major')); ?>';
function changeMajor(){//for get major by department
	dept_id =dijit.byId('dept').get('value');
		dojo.xhrPost({
		    url: url_get,			    
		    content : { 
			    'dept_id':  dept_id			    
			},
			handleAs:"json", 
		    load: function(response) {
		    	var Newmajor = {		
		    			id: 1,
						name: "IT"
				};		
				//addDataToSelectbox(dijit.byId('sender'), sender_store, Newmajor, "It");
				//dijit.byId("popupsender").hide();
			   //alert(response);
		    	//marjor_store  = getDataStorefromJSON('id','major_name', response);		
		    	//dijit.byId('major').set('store', marjor_store);				    					    		    	
		    },
		    error: function(err) {
			    alert(err);
		    	 //alert("Your message could not be sent, please try again.");
		        
		    }
		});
} 
			        			
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}
function CheckAmount(){
	if(dijit.byId('fee').get('value') < dijit.byId('discount').get('value')){
		alert("Discount cannot greather than fee value!");
		dijit.byId("discount").focus();
	}
	else{
		remain = dijit.byId('fee').get('value')-dijit.byId('discount').get('value');
	}
	dojo.byId("payment_paid").value = dojo.number.format(remain);
}
function getNewStudent(){
	if (dojo.byId("is_new").checked​){
		dojo.byId("year").value = dojo.number.format(1);
		dojo.byId("batch").value = dojo.number.format(11);
	}else{
		dojo.byId("year").value = "";
		dojo.byId("batch").value = "";
	}
	
}
</script>