<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_callteral;
echo $this->headTitle($tr->translate("SRMS_ADD_TEACHER"));
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
$techer= $this->frm_techer;
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'lecturer','action'=>'edit')); ?>" 
dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('record_row').get('value')==''){
				         alert('Please add subject !');
                         return false;
                 }
				return true;
			}else {
				return false;
			}
</script>
<table width="100%">
	<tr>
		<td>
				<fieldset style="margin-top:-13px;">
					<legend align="center" ><strong><?php echo $tr->translate("ADD_TECHER_NAME");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td style="width: 100px"><?php echo $tr->translate("Lecturer Code")?></td>
							<td><?php  echo $techer->getElement('code'); echo $techer->getElement('id');?></td>
						    <td style="width: 100px"><?php echo $tr->translate("TEACHER_KH_NAME")?></td>
							<td><?php  echo $techer->getElement('kh_name');?></td>
							<td style="width: 100px"><?php echo $tr->translate("TEACHER_EN_NAME")?></td>
							<td><?php  echo $techer->getElement('en_name');?></td>
							
						</tr>
						<tr>
							<td style="width: 100px"><?php echo $tr->translate("sex")?></td>
							<td><?php echo $techer->getElement('sex');?></td>
							<td style="width: 100px"><?php echo $tr->translate("tel")?></td>
							<td><?php echo $techer->getElement('phone');?></td>
							<td style="width: 100px"><?php echo $tr->translate("pob")?></td>
							<td><?php echo $techer->getElement('pob');?></td>
							
						</tr>
						<tr>
						<td style="width: 100px"><?php echo $tr->translate("dob")?></td>
							<td><?php echo $techer->getElement('dob');?></td>
							<td style="width: 100px"><?php echo $tr->translate("address")?></td>
							<td><?php  echo $techer->getElement('address');?></td>
							<td style="width: 5px"><?php echo $tr->translate("email")?></td>
							<td><?php  echo $techer->getElement('email');?></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("degree")?></td>
							<td><?php  echo $techer->getElement('degree');?></td>
							<td style="width: 5px"><?php echo $tr->translate("note")?></td>
							<td><?php echo $techer->getElement('note');?></td>
							<td style="width: 5px"><?php echo $tr->translate("photo")?></td>
							<td><?php  echo $techer->getElement('photo');?></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $techer->getElement('status');?></td>
						</tr>
						<tr>
							<td align="center" colspan="6">
									<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
									<div  id="test"></div>
									<input iconClass="dijitIconClear" type="button" onClick="addSubjectRow();" label="<?php echo $tr->translate('ADD');?>" dojoType="dijit.form.Button"/></td>
				    	<tr>	
						<tr>
							<td colspan="6" align="center">
								<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>
</table>
</form>
<div class="dijitHidden">
				<div data-dojo-type="dijit.Dialog"  id="pop_subject" >
			<form id="form_subject" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<table style="margin: 0 auto; width: 100%;" cellspacing="7">
					<tr>
						<td>Subject(Kh)</td>
						<td>
							<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="subject_kh" name="subject_kh" value="" type="text"></td>
					</tr>
					<tr>
						<td>Subject(En)</td>
						<td>
						   <input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="subject_en" name="subject_en" value="" type="text"></td>
					</tr>
					<tr>
						<td colspan="4" align="center">
						<input type="button" value="Save" label="Save" dojoType="dijit.form.Button"
						iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewSubject();"/>
						</td>
					</tr>
				</table></form>		</div>
		</div>
<script type="text/javascript">
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

require(["dojo/ready"], function(ready){
	ready(function(){
	 addRowSubject();
	});
});

function addRowSubject(){
		dojo.query("#test").append('');
		tmp='<table id="t_amountmoneytype" width="40%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
		tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
		tmp+='</table>';
		dojo.query("#test").append(tmp);
		thead='<th><?php echo $tr->translate("DEL");?></th>';
		thead+='<th><?php echo $tr->translate("SUBJECT NAME");?></th>';
		thead+='<th><?php echo $tr->translate("NOTE");?></th>';
		thead+='<th><?php echo $tr->translate("STATUS");?></th>';
		fund_title=1;
		
		dojo.query("#head_title").append(thead);	
		dijit.byId('record_row').attr('value','');
		<?php if(!empty($this->teacher_subject)) {
			foreach($this->teacher_subject AS $i=>$rs){?>
			r++;
			tmp='<tr style="border:1px solid #ccc; font-size:12px;" id="row_subject'+r+'">'
			tmp+="</tr>";
				dojo.query("#t_amountmoneytype").append(tmp);
			temp='<td style="width:30px !important;text-align:center;" ></td>';
			temp+='<td width="200px" ><select style=" width:98%;background:#fff; padding-left:5px;" id="subject_id'+r+'" name="subject_id'+r+'"  onchange="checkSelectOption('+r+')"  >'+subject_option+'</select></td>';
			temp+='<td width="200px"><input style=" width:98%;" type="text" name="note'+r+'" id="note'+r+'" dojoType="dijit.form.ValidationTextBox" /><input style=" width:98%;" type="hidden" name="subexist_id'+r+'" id="subexist_id'+r+'" dojoType="dijit.form.TextBox" /></td>';
			temp+='<td width="200px" ><select style="width:98%; padding-left:5px;" id="status'+r+'" name="status'+r+'" dojoType="dijit.form.FilteringSelect"  ><option value="1">Active</option><option value="0">Deactive</option></select></td>';
			
				dojo.html.set(dojo.byId("row_subject"+r),temp, {
			    parseContent: true,
			     
			});
			if(dijit.byId("record_row").get('value')!="") {
				var ids = dijit.byId("record_row").value;
				dijit.byId("record_row").attr('value',ids+','+r);
			} else { dijit.byId("record_row").attr('value',r);}
				$('#subject_id'+r).attr('value',<?php echo $rs['subject_id'];?>);
				dijit.byId('note'+r).attr('value','<?php echo $rs['note'];?>');
				dijit.byId('status'+r).attr('value','<?php echo $rs['status'];?>');
				dijit.byId('subexist_id'+r).attr('value','<?php echo $rs['id'];?>');
				
		<?php }}?>
}


temp='';
fund_title=0;
r = 0;
subject_option = '<?php echo $this->subject_opt;?>';
function addSubjectRow(){
		r++;
		tmp='<tr style="border:1px solid #ccc; font-size:12px;" id="row_subject'+r+'">'
		tmp+="</tr>";
			dojo.query("#t_amountmoneytype").append(tmp);
		temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		temp+='<td width="200px" ><select style=" width:98%;background:#fff; padding-left:5px;" id="subject_id'+r+'" name="subject_id'+r+'"  onchange="checkSelectOption('+r+')"  >'+subject_option+'</select></td>';
		temp+='<td width="200px"><input style=" width:98%;" type="text" name="note'+r+'" id="note'+r+'" dojoType="dijit.form.ValidationTextBox" /></td>';
		temp+='<td width="200px" ><select style="width:98%; padding-left:5px;" id="status'+r+'" name="status'+r+'" dojoType="dijit.form.FilteringSelect"  ><option value="1">Active</option><option value="0">Deactive</option></select></td>';
		
			dojo.html.set(dojo.byId("row_subject"+r),temp, {
		    parseContent: true,
		     
		});
		if(dijit.byId("record_row").get('value')!="") {
			var ids = dijit.byId("record_row").value;
			dijit.byId("record_row").attr('value',ids+','+r);
		} else { dijit.byId("record_row").attr('value',r);}
		
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_subject"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_subject"+index).remove();
	}
}
subject_id = 0;
function checkSelectOption(index){
	id = $('#subject_id'+index).val();
	if(id==-1){
		subject_id=index;
    	dijit.byId("pop_subject").show();
    }
}
var url_subject = '<?php echo $this->url(array('module'=>'global','controller'=>'subject','action'=>'addsubject')); ?>';
function addNewSubject(){
	if(dijit.byId('form_subject').validate()){
		subject_id
		dojo.xhrPost({
			url:url_subject,
			form: dojo.byId("form_subject"),
			handleAs:"json",
			load: function(data) {
				 $('#subject_id'+subject_id).append($("<option></option>").attr("value",data).attr("selected",true).text(dijit.byId('subject_kh').get('value')+'-'+dijit.byId('subject_en').get('value')));
				dijit.byId('form_subject').reset();
				dijit.byId('pop_subject').hide();
			},
			error: function(err) {
				alert('Insert fail');
			}
		});
	}
	
}

</script>