<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_WUREGISTER')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require('dojox.form.BusyButton');
	//dojo.require("dijit.Dialog");
	
	var major_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	var stucard_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->student_card));?> );

	dojo.addOnLoad(function(){
		   // document.musicPrefs.other.value="Afrobeat";
			//getStudentBYId();
		});
	dojo.ready(function(){
	/*new dijit.form.FilteringSelect({
        store: major_store,
        autoComplete: true,                        
        required: true,
        id: "major",
        name: "major",           
        class: 'fullside',            
        missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
        onChange: function() {                
        }
    }, "major");*/

	var batch = dojo.byId("batch"); 
		dojo.connect(batch, "onkeyup", function(evt){			
			getTuitionFee();
	});	

	value_invoice = '<?php echo $this->invoice_num;?>';
	dijit.byId('reciept_no').attr('value',value_invoice);
	dijit.byId('reciept_no').set('readOnly',true);
	}); 

	var txtstudent_card = dojo.byId("stu_id"); 
	dojo.connect(txtstudent_card, "onkeyup", function(evt){	
			getStudentBYId();
			
	});
	
	var url_getstu_info = '<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'get-studentinfo')); ?>';
	function getStudentBYId(){
		   student_id = dijit.byId("stu_id").get('value');
		   if(student_id==''){
			   return false;
			   }
				dojo.xhrPost({
				   content : {'student_card':  student_id},
				    url: url_getstu_info,			    
					handleAs:"json",
				    load: function(response) {	
					    dijit.byId("kh_name").attr('value',response.stu_khname);
					    dijit.byId("en_name").attr('value',response.stu_enname);
					    dijit.byId('sex').set('value', response.sex);
					    dijit.byId("phone").attr('value',response.phone);
					    dijit.byId("metion").attr('value',response.mention);
					    dijit.byId('year').attr('value',response.year);
					    dijit.byId('degree').set('value', response.degree);
					    dijit.byId('batch').set('value',response.batch);
					    dijit.byId('dept').set('value',response.faculty_id);
					    dijit.byId('session').set('value',response.session);
				    },
				    error: function(e) {
					    alert(e);
				    }
				});
	}
	function setValueTo(){
		if(dijit.byId('kh_name').item != null){
		alert(items.name);
		dijit.byId("sender_code_no").attr('value', dijit.byId('sender_name').item.code_no);
		}
	}
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'wu-register')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset style="background:#DFF7FD;">
					<legend align="center"><strong><?php echo $tr->translate("OFFICIAL_RECEIPT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD; padding:10px;" cellspacing="7" >
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("NEW_STUDENT");?></td>
							<td><?php echo $register->getElement('is_new');?>
								&nbsp;&nbsp;&nbsp;&nbsp;<label for='is_subsped'>Subspend</label><?php echo $register->getElement('is_hold');?>
							</td>
							<td style="width: 160px"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td><?php echo $register->getElement('stu_id');?></td>
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DOB");?></td>
							<td><?php echo $register->getElement('dob');?></td>
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><?php echo $register->getElement('phone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEGREE");?><label class="red">*</label></td>
							<td><?php echo $register->getElement('degree');?></td>
							<td><?php echo $tr->translate("BATCH");?><label class="red">*</label></td>
							<td><?php echo $register->getElement('batch');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("FACULTIES");?><label class="red">*</label></td>
							<td><?php echo $register->getElement('dept');?></td>
							<td><?php echo $tr->translate("MAJOR_C");?><label class="red">*</label></td>
							<td><!--<input id="major" >--><?php echo $register->getElement('metion');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("YEARTH");?></td>
							<td><?php echo $register->getElement('year');?></td>
							<td><?php echo $tr->translate("SESSION");?></td>
							<td><?php echo $register->getElement('session');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PAYMENT_TERM");?><label class="red">*</label></td>
							<td><?php echo $register->getElement('payment_term');?></td>
							<td><?php echo $tr->translate("TUITION_FEE");?></td>
							<td><?php echo $register->getElement('tuitionfee');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("DISCOUND");?></td>
							<td title='Ex: 20 or 10%'><?php echo $register->getElement('discount');?></td>
							<td><?php echo $tr->translate("AMOUNT_PAID");?></td>
							<td><?php echo $register->getElement('payment_paid');?>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate('IN_WORDS');?></td>
							<td><?php echo $register->getElement('paid_kh');?></td>
							<td><?php echo $tr->translate("REMARK");?></td>
							<td><?php echo $register->getElement('remark');;?></td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input type="button" onclick="SubmitRegister();" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 <input type="button" value="រក្សាទុក & បោះពុម្ព" label="រក្សាទុក & បោះពុម្ព" id="busyButton" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
function SubmitRegister(){
	if(dijit.byId('office_receipt').validate()){
		if(dijit.byId('tuitionfee').get('value') < dijit.byId('discount').get('value')){
			alert("Discount cannot greather than fee value!");
			return false;
		}
		dijit.byId('office_receipt').submit();
	}
}
function printSave(){		
	if(dijit.byId('office_receipt').validate()) {
		dojo.byId("lb_receipt_no").innerHTML = dijit.byId("reciept_no").get('value');
		//dojo.byId("lb_paydate").innerHTML = dijit.byId("pay_date").value;
		dojo.byId("lb_kh_stuname").innerHTML = dijit.byId("kh_name").get('value');
		dojo.byId("lb_en_stuname").innerHTML = dijit.byId("en_name").get('value');
		dojo.byId("lb_student_id").innerHTML = dijit.byId("stu_id").get('value');
		dojo.byId("lb_sex").innerHTML = dijit.byId('sex').attr('displayedValue');
		//var mkh = new Array('មករា', 'កុម្ភៈ', 'មីនា', 'មេសា', 'ឧសភា', 'មិថុនា', 'កក្កដា', 'សីហា', 'កញ្ញា', 'តុលា', 'វិច្ឆិកា', 'ធ្នូរ');
		var d = dojo.byId("dob").value.split('/');
		dojo.byId("lb_dob").innerHTML = d[0] + "/" + d[1] +"/"+d[2];
		dojo.byId("lb_degree").innerHTML = dijit.byId('degree').attr('displayedValue');
		dojo.byId("lb_phone").innerHTML = dijit.byId("phone").get('value');
		dojo.byId("lb_major").innerHTML = dijit.byId('dept').attr('displayedValue');
		
		dojo.byId("lb_batch").innerHTML = dijit.byId("batch").get('value');
		dojo.byId("lb_year").innerHTML = dijit.byId("year").get('value');
		dojo.byId("lb_session").innerHTML = dijit.byId('session').attr('displayedValue');
		dojo.byId("lb_term").innerHTML = dijit.byId('payment_term').attr('displayedValue');
		dojo.byId("lb_fee").innerHTML = dijit.byId("tuitionfee").get('value');
		dojo.byId("lb_discound").innerHTML = dijit.byId("discount").get('value');
		dojo.byId("lb_amount_paid").innerHTML = dijit.byId("payment_paid").get('value');
		//dojo.byId("lb_in_khmer").innerHTML = dijit.byId("paid_kh").value;
		//dojo.byId("lb_byuser").innerHTML = dijit.byId("kh_name").value;
		dijit.byId("terms").show();	
	}
	
}
</script>
<div class="dijitHidden">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT");?>'" id="terms" >
		<div id="divPrint" style="width: 21cm; height: 14cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 10px;width: 91%; display: block;
						margin-top: -12px; line-height: 25px;}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -5px;}
​​               .print td{ font:bold 11px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			</style>	
			<table class="print" bgcolor="fef7e4" cellspacing="5" style="width: 21cm;height: 14cm; font-size:13px; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px;">
					<tr height="50px">
						<td><img src="<?php echo $base_url.'/images/logo-letter.gif';?>" width="100%"/></td>
					   	<td align="center" colspan="2">	
				            <strong style="font:bold 20px 'Kh Muol';"><?php echo $keycode['reciept_kh'];?></strong><br/>
							<strong style="font-size: 20px;font-weight:bold"><?php echo $keycode['reciept_en'];?></strong><br/>
			            </td>
			            <td></td>
				   </tr>
				   <tr height="50px">
						<td>
							<div style="border:1px solid #e14109;font-size:8pt; width:170px;; padding:10px; text-align: center;">
			            		<label style=" color:#e14109;">ប្រាក់ដែលបង់រួចមិនអាចដកវិញបានទេ</label><br />
			            		<label style=" color:#e14109; text-align: center">Nonrefundable</label>
			            	</div></td>
					   	<td></td>
			            <td align="center" colspan="2">
			            	<div style="border:1px solid rgba(14, 0, 107, 1);font-size:12; width:160px; border-radius:10px; padding:10px;">
			            		Receipt N<sup>o</sup> : <label style=" color:#e14109;" id="lb_receipt_no"></label><br />
			            		Date : <?php echo date("d-M-Y");?>
			            	</div>
			            </td>
				   </tr>
					<tr>
						<td width="15%"><label class="khmerbold">នាម - គោត្តនាម</label><div class="h"></div>Name(First|Last):</td>
						<td  width="35%">&nbsp;<label class="value khmerbold" id="lb_kh_stuname" ></label></td>
						<td  width="15%"><label class="khmerbold">អក្សរឡាតាំង </label><div class="h"></div>In English</td>
					   	<td  width="35%"><strong>&nbsp; <label id="lb_en_stuname" class="value"></label></strong></td>
				   </tr>
				   <tr>
						<td><label class="khmerbold">អត្តលេខ</label><div class="h"></div>ID N<sup>o</sup></td>
						<td>
							<table width="100%">
								<tr>
									<td width="50%">&nbsp;<label id="lb_student_id" class="value" ></label></td>
									<td width="25%">&nbsp;&nbsp;<label class="khmer">ភេទ</label><div class="h"></div>&nbsp;&nbsp;Sex&nbsp; </td>
									<td width="20%">&nbsp;<label id="lb_sex" class="value"></label></td>
									<td width="5%"></td>
								</tr>
							</table>
						</td>
						<td><label class="khmer">ថ្ងៃខែឆ្នាំកំណើត</label><div class="h"></div>Date of Birth</td>
					   	<td>&nbsp; <label id="lb_dob" class="value"></label></td>
				   </tr>
				   <tr>
				   		<td><label class="khmerbold">ជាសិស្សថ្នាក់</label><div class="h"></div>Degree</td>
						<td>&nbsp; <label id="lb_degree" class="value khmer"></label></td>
						<td><label class="khmer">ទូរស័ព្ទ</label><div class="h"></div>Phone</td>
						<td>&nbsp; : <label id="lb_phone" class="value"></label></td>
				   </tr>
				    <tr>
				    	<td><label class="khmerbold">ជំនាញ</label><div class="h"></div>Major
				    		&nbsp; 
				    	</td>
						<td colspan="3">
							<table width="100%" >
								<tr>
									<td width="195px"><label id="lb_major" class="values"></label></td>
									<td><label class="khmer">&nbsp;ជំនាន់</label><div class="h"></div>&nbsp;Batch&nbsp;</td>
									<td width="10px"><label id="lb_batch" class="values"></label></td>
									<td><label class="khmer">&nbsp;ឆ្នាំទី</label><div class="h"></div>&nbsp;Year&nbsp; </td>
									<td><label id="lb_year" class="values" ></label></td>
									<td><label class="khmer">&nbsp;ពេល</label><div class="h"></div>&nbsp;Session&nbsp;</td>
									<td><label id="lb_session" class="values khmer"></label></td>
									<td width="10px"></td>
								</tr>
							</table>
						</td>
				   </tr>
				   <tr>
						<td><label class="khmerbold">បង់ជា</label><div class="h"></div>Payment Term</td>
						<td>&nbsp;  <label id="lb_term" class="value khmer"></label></td>
						<td><label class="khmerbold">តម្លៃសិក្សា</label><div class="h"></div>Tuition Fee</td>
						<td><strong class="value">&nbsp; $ <label id="lb_fee"​ ></label></strong></td>
				   </tr>
				   <tr>
						<td><label class="khmerbold">បញ្ចុះតម្លៃ</label><div class="h"></div>Discount</td>
						<td><strong class="value">&nbsp; $<label id="lb_discound"></label></strong></td>
						<td><label class="khmer">ទឹកប្រាក់ត្រូវបង់</label><div class="h"></div>Amount Paid</td>
						<td><strong class="value">&nbsp;  $ <label id="lb_amount_paid"></label></strong></td>
				   </tr>
				   <tr>
						<td>ឈ្មោះអ្នកទទូល :</td>
						<td>&nbsp; : <?php $session_user=new Zend_Session_Namespace('auth');
			        			$username = $session_user->first_name; echo $username;?></td>
						<td>Paid Date</td>
						<td>&nbsp; : 23/02/2014</td>
				   </tr>
				  <?php echo $this->footer;?>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
	</div>
</div>

<script>
function calculatePrice() {
	var total = $('#tuitionfee').val();
	var ds = $('#discount').val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				return after_discount;

			}else{
				after_discount = total - ds;
				return after_discount;
			}
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
				return after_discount;
			}else{
				batch
				after_discount = total;
				return after_discount;
				}
		}
	}
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}
function CheckAmount(){
	remain=calculatePrice();
	if(dijit.byId('tuitionfee').get('value') < dijit.byId('discount').get('value')){
		alert("Discount cannot greather than fee value!");
		dijit.byId("discount").focus();
		return false;
	}
	else{
		//remain = dijit.byId('tuitionfee').get('value')-dijit.byId('discount').get('value');
	}
	dojo.byId("payment_paid").value = dojo.number.format(remain);
	money_kh = $('#payment_paid').val();
	money_khmer=read_money_in_khmer(money_kh);
	dijit.byId('paid_kh').attr('value',money_khmer.trim()+'ដុល្លាគត់');
}
function getNewStudent(){
	if (dojo.byId("is_new").checked){
		dojo.byId("year").value = dojo.number.format(1);
		dojo.byId("batch").value = dojo.number.format(11);
		getTuitionFee()
	}else{
		dojo.byId("year").value = "";
		dojo.byId("batch").value = "";
	}
}

var url_major = '<?php echo $this->url(array('module'=>'registrar','controller'=>'index','action'=>'get-majors')); ?>';
function changeMajor(){
	getTuitionFee();
	/*dept_id = dijit.byId('dept').get('value');
			dojo.xhrPost({
			    url: url_major,			    
			    content : { 
				    'dept_id':  dept_id	    
				},
				handleAs:"json", 
			    load: function(response) {
			    	//major_store  = getDataStorefromJSON('id','name', response);
					//dijit.byId('major').set('store',major_store); 					    		    					    		    	
			    },
			    error: function(err) {
			    	 alert(err);
			        
			    }
			});*/
}
var url_add_sender = '<?php echo $this->url(array('module'=>'transfer','controller'=>'index','action'=>'addnewsender')); ?>';//for get payment date of sender 
function saveSender(){
		 sender_name=dijit.byId('sender_name').get('value');
			 sender_tel=dijit.byId('sender_tel').get('value');
				dojo.xhrPost({
				    url: url_add_sender,	
				    content : { 
					    'sender_name': sender_name,
					    'sender_tel': sender_tel			    
					},		    
					handleAs:"json", 
				    load: function(response) {	
				    	var Newsender = {		
				    			id: sender_name,
								name: sender_name
						};		
						addDataToSelectbox(dijit.byId('sender'), sender_store, Newsender, sender_name);
						dijit.byId("popupsender").hide();
				    },
				    error: function(e) {
					    alert("You can not add new sender !");
				        
				    }
				}); 
}
var url_add_getfee = '<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'get-tuitionfee')); ?>';//for get payment date of sender 
function getTuitionFee(){
	degree=dijit.byId('degree').get('value');
	faculty_id=dijit.byId('dept').get('value');
	//major=dijit.byId('major').value;
	batch=dijit.byId('batch').get('value');
	metion=dijit.byId('metion').get('value');
	payment_term=dijit.byId('payment_term').get('value');
	
	//if(degree=='' || faculty_id=='' || major=='' || batch=='' || payment_term==''){
	if(degree=='' || faculty_id=='' || batch=='' || payment_term==''){
		
	}else{
		dojo.xhrPost({
		    url: url_add_getfee,	
		    content : { 
			    'degree':degree ,
			    'faculty_id':faculty_id,
			    //'major':major,
			    'batch':batch,
			    'payment_term':payment_term ,
			    'metion':metion,
			},		    
			handleAs:"json", 
		    load: function(response) {	
		    	dijit.byId('tuitionfee').attr('value',response.fee);
		    	CheckAmount();
		    },
		    error: function(e) {
			    alert(e);
		    }
		});
	}			 
}
</script>