<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report Tuition Fee'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<form  id='rpt_daily' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'report','action'=>'rpt-daily')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div style="width:100%; background:none repeat scroll 0% 0% rgba(234, 255, 253, 1);">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
				<fieldset style="background: none;height: 600px;overflow: scroll;overflow-x:hidden;">
							<legend align="center" ><strong><?php echo $tr->translate("");?></strong></legend>
							<table style="width:30cm;background:#fff; margin: 0 auto; border: 1px dotted #ccc;">
								<tr style="font-size: 13px;">
									<td align="left" width="20%" >
										<strong>សាកលវិទ្យាល័យ វេស្ទើន</strong><br />
										<strong>Western University</strong><br />
									</td>
									<td align="center" colspan="2">
										<strong>DAILY COLLECTION REPORT</strong><br />
										<strong>Date:</strong><br />
									</td>
									<td align="right" width="20%">
										<strong>2013</strong>
									</td>
									
								</tr>
								<tr>
									<td>
										<br><br>
									</td>
								</tr>
								<tr>
									<td colspan="4">
													<table style="width:30cm;background:#fff; margin: 0 auto; border: 1px solid #ccc;">
														<tr style="font-size:12px;" >
															<td align="left">
																<strong>Name:srey pov</strong><br>
																<strong>ID:B8-9987</strong><br>
																<strong>From:Takeo</strong><br>
															</td>
															<td align="center"><br>
																<strong>Compus:Toulkok</strong><br>
															</td>
															<td align="right">
																<strong>Report No:srey pov</strong><br>
																<strong>Report Date:B8-9987</strong><br>
																<strong>Rate($/Reil):4100រ</strong><br>
															</td>
														</tr>
														<tr>
												<td colspan="4">
													<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
														<tr style="font-size:12px; height: 30px;" align="center" >
															<th rowspan="2">N<sup>o</sup></th>
															<th rowspan="2">Name</th>
															<th rowspan="2">ID</th>
															<th rowspan="2">Class</th>
															<th rowspan="2">Receip N<sup>o</sup></th>	
															<th rowspan="2">Item code</th>
															<th rowspan="2">Item Description</th>
															<th rowspan="2">U.P.</th>
															<th rowspan="2">Qty or Percent</th>					
															<th rowspan="2">Amount</th>
															<th rowspan="2">Discount</th>
															<th rowspan="2">Total Per Receipt</th>
															<th rowspan="2">Total Per Student</th>
														</tr>
														<tr></tr>
													
														<?php for ($i=1;$i<20;$i++){?>
														<tr align="center" style="font-size:11px;height:23px;"​>
															<td><?php echo $i;?></td>
															<td>Raty</td>
															<td>009</td>
															<td>(SR)</td>
															<td>86667</td>
															<td>7687</td>
															<td>SR.Testing for GEP-SP1</td>
															<td>1.00</td>
															<td></td>
															<td>1.00</td>
															<td></td>
															<td>1.00</td>
															<td>1.00</td>
															
														</tr>
														<?php }?>
														<tr style="font-size:12px;" align="center">
															<td colspan="4"><strong>Total Collected with Receipts</strong></td>
															<td colspan="5"><strong> (1),(2),(3)</strong></td>
															<td><strong>$342</strong></td>
															<td><strong></strong></td>
															<td><strong>$342</strong></td>
															<td><strong>$342</strong></td>
														
														</tr>
													</table>
												</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr><td><br /></td></tr>
									<tr style="font-size:11px;" >
										      	 <td align="left" width="8%">
										      	 	<strong>(2)Total Remitted</strong>
										      	 </td>
												<td width="33%" align="left">
													<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" align="left" >
														<tr style="font-size:12px; height: 30px;" align="center" >
															<td>Breack Down</td>
															<td width="12%">1</td>
															<td width="12%">2</td>
															<td width="12%">3</td>
															<td width="12%">4</td>
															<td width="12%">5</td>
														</tr>
														<tr align="center">
															<td rowspan="3">incash cos per ticked attached <br />check & cradit card<br />paid out</td>
															<td>1</td>
															<td>2</td>
															<td>3</td>
															<td>4</td>
															<td>5</td>
														</tr>
														<tr align="center">
															
															<td>1</td>
															<td>2</td>
															<td>3</td>
															<td>4</td>
															<td>5</td>
														</tr>
														<tr align="center">
															
															<td>1</td>
															<td>2</td>
															<td>3</td>
															<td>4</td>
															<td>5</td>
														</tr>
													</table>	
												</td>
												<td  align="center" width="25%">
														<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
															<tr style="font-size:12px;height: 22px;" align="center" >
																<td >Sub Total</td>
															</tr>
															<?php for ($e=1;$e<4;$e++){?>
															<tr align="center" style="height: 21.5px;">
																<td><?php echo $e;?></td>	
															</tr>
															<?php }?>
														
														</table>
												</td>
												<td  align="right" width="27%">
														<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;" >
															<tr style="font-size:12px; height: 30px;" align="center">
																<td>$345</td>
																<td>$345</td>
																<td style="border-bottom: double;border-top: double;" bgcolor="#fc0">$345</td>
															</tr>
														</table>
												</td>
										</tr>
										<tr><td><br /></td></tr>
										<tr style="font-size:11px;" >
										      	 <td align="left" width="8%">
										      	 	<strong>(3)Total Posted A/C</strong>
										      	 </td>
												<td width="33%" align="left">
													<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" align="left" >
														<tr style="font-size:12px; height: 30px;" align="center" >
															<td colspan="4" >$546<br />$546<br />$546<br />$546<br /></td>
															<td colspan="4">$546<br />$546<br />$546<br />$546<br /></td>
															<td colspan="4">$546<br />$546<br />$546<br />$546<br /></td>
															<td colspan="4">$546<br />$546<br />$546<br />$546<br /></td>
														</tr>
														
													</table>	
												</td>
												<td  align="center" width="25%">
														<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
															<tr style="font-size:12px; height: 18px;" align="center" >
																<td >Discount</td>
															</tr>
															
															<tr align="center" style="height: 21.5px;">
																<td colspan="3">1<br />2<br />3<br /></td>	
															</tr>
															
														
														</table>
												</td>
												<td  align="right" width="27%">
														<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;" >
															<tr style="font-size:12px; height: 30px;" align="center">
																<td >$345</td>
																<td>$345</td>
																<td style="border-bottom: double;border-top: double;">$345</td>
															</tr>
														</table>
												</td>
										</tr>		
							</table>
				</fieldset>		
				</td>
			</tr>
		</table>
	</div>	
</form>
