<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_UPDATE_ROOM')); 
?>	
<?php  $update_room= $this->update_room;?>
<form  id='update_room' action="<?php echo $this->url(array('module'=>'global','controller'=>'room','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="40%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("UPDATE_CLASSNAME_NAME");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td style="width: 100px"><?php echo $tr->translate("CLASSNAME")?></td>
							<td><?php  echo $update_room->getElement('classname');?></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $update_room->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="submit" value="<?php echo $tr->translate('GO_EDIT');?>" label="<?php echo $tr->translate('GO_EDIT');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("update_room").submit();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
