<!DOCTYPE html>
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title>index of project-info</title>
<link href="<?php echo $this->baseUrl();?>/cssmenu/template.css" media="screen" rel="stylesheet" type="text/css">

	
<style>
	input.tab5bold.hasDatepicker {
		background:none;		
	}
</style>
</head>
<body>  
<div id="menu">
	<ul>
		<li class="current">
							<a title="Project Info" href="#">
								<span>Project Info</span>
							</a>
						</li><li class="link">
						<a title="Budget" href="#">
							<span>Budget</span>
						</a>
				  </li><li class="link">
							<a title="Procurement" href="#">
								<span>Procurement</span>
							</a>
						</li><li class="link">
						<a title="Public Sector Debt Statistics" href="#">
							<span>PSDS</span>
						</a>
					</li><li class="link">
						<a title="Report" href="#">
							<span>Report</span>
						</a>
					</li><li class="link">
						<a title="Inventory" href="http://pdms.resolvocam.com/inventory/tax-exemption">
							<span>Inventory</span>
						</a>
					   </li><li class="link">
						<a title="Reference" href="http://pdms.resolvocam.com/reference/poc">
							<span>Reference</span>
						</a>
					 </li><li class="link">
					<a title="Salary Supplement" href="http://pdms.resolvocam.com/poc/poc-director">
						<span>Salary Supplement</span>
					</a>
				</li><li class="link">
						<a title="Personnel" href="http://pdms.resolvocam.com/personel">
							<span>Personnel</span>
						</a>
					</li><li class="link">
						<a title="Analysis" href="http://pdms.resolvocam.com/analysis/query">
							<span>Analysis</span>
						</a>
					</li><li class="link">
					<a title="Result Management Framework" href="http://pdms.resolvocam.com/rmf/rmf">
						<span>RMF</span>
					</a>
				</li><li class="link">
					<a title="Share" href="http://pdms.resolvocam.com/share/share">
						<span>Share</span>
					</a>
				</li><li class="link">
					<a title="Public Private Partnership" href="http://pdms.resolvocam.com/botboo">
						<span>PPP</span>
					</a>
				</li><li class="link">
					<a title="More" href="http://pdms.resolvocam.com/more/donor">
						<span>More</span>
					</a>
				</li>	</ul>
</div>	
</body></html>