<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Loan Management System</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-responsive.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-default.css" rel="stylesheet" id="style_color" />
   <link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/images/icon.ico" type="image/x-icon"/>
<style>
.tundra .dijitBorderContainer-child{
	 overflow: hidden;
}
</style>
 </head>
<body class="fixed-top">
   <div id="container" class="row-fluid">
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE CONTENT-->
            <div class="row-fluid">
                <!--BEGIN METRO STATES-->
                <div class="metro-nav metro-fix-view">
                    <div class="metro-nav-block nav-block-green long">
                        <a href="<?php echo $this->baseUrl();?>/group/client/add" style="text-align: center;" class="text-center" data-original-title="">
                            <span class="value">
                                <i class="icon-user"></i>
                            </span>
                        </a>
                        <div class="status" align="center">បង្កើតឈ្មោះអតិថិជន</div>
                    </div>
                    <div class="metro-nav-block nav-block-orange">
                        <a href="<?php echo $this->baseUrl();?>/group/Callteral/add" data-original-title="">
                            <i class="icon-user"></i>
                            <div class="info"></div>
                            <div class="status">ទ្រពបញ្ចំអតិថិជន</div>
                        </a>
                    </div>

                   <div class="metro-nav-block nav-block-green">
                       <a href="#" data-original-title="">
                           <i class="icon-comments-alt"></i>
                           <div class="info"></div>
                           <div class="status">Comments</div>
                       </a>
                   </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="#" data-original-title="">
                            <i class="icon-tasks"></i>
                            <div class="info">$37624</div>
                            <div class="status">Stock</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-yellow">
                        <a href="#" data-original-title="">
                            <i class="icon-tags"></i>
                            <div class="info"></div>
                            <div class="status">Sales</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-grey">
                        <a href="#" class="text-center" data-original-title="">
                            <i class="icon-phone"></i>
                            <div class="status">Phone</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-red double">
                        <a href="#" data-original-title="">
                            <i class="icon-bar-chart"></i>
                            <div class="info"></div>
                            <div class="status">Update</div>
                        </a>
                    </div>

                    <div class="metro-nav-block nav-block-orange">
                        <a href="#" data-original-title="" class="text-center">
                            <i class="icon-star-empty"></i>
                            <div class="status">Rattings</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-purple double">
                        <a href="#" data-original-title="">
                            <i class="icon-eye-open"></i>
                            <div class="info"></div>
                            <div class="status">Unique Visitor</div>
                        </a>
                    </div>

                    <div class="metro-nav-block nav-block-red">
                        <a href="#" data-original-title="">
                            <i class="icon-shopping-cart"></i>
                            <div class="info"></div>
                            <div class="status">New Order</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-grey">
                        <a href="#" data-original-title="">
                            <i class="icon-remove-sign"></i>
                            <div class="info"></div>
                            <div class="status">Cancelled</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-purple">
                        <a href="#" data-original-title="" class="text-center">
                            <i class="icon-cogs"></i>
                            <div class="status">Settings</div>
                        </a>
                    </div>

                    <div class="metro-nav-block nav-block-blue">
                        <a href="#" data-original-title="">
                            <i class="icon-shopping-cart"></i>
                            <div class="info"></div>
                            <div class="status">New Order</div>
                        </a>
                    </div>

                    <div class="metro-nav-block nav-block-green double">
                        <a href="#" data-original-title="">
                            <i class="icon-external-link"></i>
                            <div class="info">$53412</div>
                            <div class="status">Total Profit</div>
                        </a>
                    </div>
                     <div class="metro-nav-block nav-block-blue double">
                        <a href="#" data-original-title="">
                            <i class="icon-external-link"></i>
                            <div class="info">$53412</div>
                            <div class="status">Total Profit</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-grey">
                        <a href="#" class="text-center" data-original-title="">
                            <i class="icon-dashboard"></i>
                            <div class="status">Dashboard</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-orange">
                        <a href="#" class="text-center" data-original-title="">
                            <i class="icon-signout"></i>
                            <div class="status">Sign Out</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-yellow">
                        <a href="#" class="text-center" data-original-title="">
                            <i class=" icon-puzzle-piece"></i>
                            <div class="status">Warning</div>
                        </a>
                    </div>
                </div>

                <div class="space10"></div>
                <!--END METRO STATES-->
            </div>
            <!-- END PAGE CONTENT-->
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->  
   </div>
   <!-- END CONTAINER -->

   <!-- BEGIN FOOTER -->
   <div id="footer">
       2014 &copy; SRMS.
   </div>
   <!-- END FOOTER -->

   <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <script src="<?php echo $this->baseUrl()?>/js/jquery-1.8.3.min.js"></script>
   <script src="<?php echo $this->baseUrl()?>/js/jquery.nicescroll.js" type="text/javascript"></script>
   <script src="<?php echo $this->baseUrl()?>/assets/bootstrap/js/bootstrap.min.js"></script>

   <!-- ie8 fixes -->
   <!--[if lt IE 9]>
   <script src="js/excanvas.js"></script>
   <script src="js/respond.js"></script>
   <![endif]-->

   <!--common script for all pages-->
   <script src="<?php echo $this->baseUrl()?>/js/common-scripts.js"></script>
   <!-- END JAVASCRIPTS -->   
</body>
<!-- END BODY -->
</html>