<title>Edit Label</title>
<fieldset>
		<legend><strong>Edit Label</strong></legend>
<form action="<?php echo $this->url(array('module'=>'setting','controller'=>'Label','action'=>'edit')); ?>" method="post" enctype="application/x-www-form-urlencoded" >
<table width="100%">
	<tr>
		<td>Label Name</td>
		<td>
			<input type="text" required="true" name="label_name"​  
												dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->rs['keyValue'];?>"
												missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពិស្ដាជាខ្មែរ!" class="fullside" />
		   <input type="hidden" name="id" value="<?php echo $this->rs['code'];?>"  />
		   <input type="submit" value="រក្សាទុក" label="រក្សាទុក" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
										
		</td>
	</tr>
</table>
</form>
</fieldset>