<title>SRMS System | Add Module Assignment</title>
<?php $form=$this->form; ?>
<style>
fieldset.fifthy {	
	border-right: 0px;
	width: 50%;	
}
table.user td{
	vertical-align: top;
	padding-left: 5px;	   
}
</style>       
<script language="javascript">
      var temp=-1;
   
	function validateUser(field)
	{
		if(temp==1) return '* User name already exist!';
		else temp==-1;
	}
    function validatePassword(field)
	{
    	var com=$('#confirm_password').val();
    	var pwd=$('#password').val();
		if(com!=pwd) return '* Password mismatch!';		 
	}
</script>

<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	Application_Model_Decorator::removeAllDecorator($form);
	$cancel_url=$this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'user-access',
		'action'=>'index',
	)); 	
?>
<br/>
<form id="frm" action="<?php echo $form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded" >	
	<div class="btn" align="right">
		    <button type="submit" class="positive" name="save">
		        <img src="<?php echo BASE_URL?>/images/icon/apply2.png" alt=""/>
		        <?php echo $tr->translate('SAVE');?>
		    </button>												   						
		    <a href="<?php echo $cancel_url; ?>" class="negative">
		        <img src="<?php echo BASE_URL?>/images/icon/cross.png" alt=""/>
		        <?php echo $tr->translate('CANCEL');?>
		    </a>
   </div>
   <fieldset>
		<legend><?php echo $tr->translate('USER_ACCESS');?></legend>
		<table>
			<tr>
				<td id="field"><?php echo $tr->translate('USER_TYPE');?></td>
				<td class="add-edit"><?php echo $form->getElement('user_type_id');?></td>				
			</tr>
			<tr>
				<td id="field"><?php echo $tr->translate('USER_ACCESS');?></td>
				<td class="add-edit"><?php echo $form->getElement('acl_id');?></td>				
			</tr>
		</table>
	</fieldset>		
</form>