<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$cancel_url=$this->url(array('module'=>'rsvAcl','controller'=>'acl','action'=>'index',));
	$frm_dept = $this->frm_dept;
?>
<title><?php echo $tr->translate("SRMS")." | ".$tr->translate("ADD_DEPT");?></title>
<div class="btn" align="right">
	<input  type="button" value="ត្រលប់​ក្រោយ" label="ត្រលប់​ក្រោយ" id="btadd" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $cancel_url; ?>';"/>
</div>
<form action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">										
			if(this.validate()) {								
				return true;
			}
			return false;
	</script>
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_DEPT");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%">
									<tr>
										<td><?php echo $tr->translate("EN_NAME")?></td>
										<td><?php echo $frm_dept->getElement("en_name");?></td>
										<td><?php echo $tr->translate("KH_NAME")?></td>
										<td><?php echo $frm_dept->getElement("kh_name");?></td>
									</tr>
									
									<tr>
										<td>Action</td>
										<td>
											<input type="text" required="true" name="action" id="action" placeholder="Action" 
											dojoType="dijit.form.ValidationTextBox" value=""
											missingMessage="Invalid Action!" class='fullside' />
										</td>
									</tr>	
									<tr>
										<td><?php echo $tr->translate("DEPT_NAME")?></td>
										<td>
										<?php echo $frm_dept->getElement("status");?>
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>	
	<input type="hidden" name="user_type_id" value="<?php echo $this->user_edit['id'];?>" />
</form>