<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_ROOM')); 
?>	

<?php  $classname= $this->frm_classname;?>
<form  id='add_room' action="<?php echo $this->url(array('module'=>'global','controller'=>'index','action'=>'add-room')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="40%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("ADD_CLASSNAME_NAME");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td style="width: 100px"><?php echo $tr->translate("CLASSNAME")?></td>
							<td><?php  echo $classname->getElement('classname');?></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $classname->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									 iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"index",'action'=>'room-list'),null,true); ?>';" />
								<input type="submit"  label="<?php echo $tr->translate('GO_SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("add_room").submit();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
