<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SRMS_EDET_FACULTY"));
?>	
<?php  $frm_dept= $this->frm_dept;?>
<form  id='edit-dept' action="<?php echo $this->url(array('module'=>'global','controller'=>'index','action'=>'edit-dept')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="55%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("EDET_FACULTY");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("FACULTY_ENNAME");?></td>
							<td>
								<?php echo $frm_dept->getElement("en_name");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("FACULTY_KHNAME");?></td>
							<td>
								<?php echo $frm_dept->getElement("kh_name");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SHORTCUT");?></td>
							<td><?php echo $frm_dept->getElement("shortcut");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS");?></td>
							<td><?php echo $frm_dept->getElement("status");?>
								<?php echo $frm_dept->getElement("dept_id");?>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center"><br />
								<input iconClass="dijitIconUndo" type="button" value="<?php echo $tr->translate("GO_BACK");?>" 
								label="<?php echo $tr->translate("GO_BACK");?>" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"index",'action'=>'dept-list'),null,true); ?>';"/>
								
								<input type="submit"  label="<?php echo $tr->translate("GO_EDIT");?>" id="submitButton" 
								dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>