<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_PROVINCE')); 
?>
<?php  $province= $this->frm_province;?>
<form id="add_province" action="<?php echo $this->url(array('module'=>'global','controller'=>'index','action'=>'edit-province')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_PROVINE_NAME");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%">
									<tr>
										<td><?php echo $tr->translate("EN_PROVINCE")?></td>
										<td><?php echo $province->getElement("en_province");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("KH_PROVINCE")?></td>
										<td><?php echo $province->getElement("kh_province");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("STATUS")?></td>
										<td>
										<?php echo $province->getElement("status");?>
										</td>
									</tr>
									<tr>
										<td colspan="2" align="center">
											<input iconClass="dijitIconUndo" type="button" value="<?php echo $tr->translate("GO_BACK");?>" 
											label="<?php echo $tr->translate("GO_BACK");?>" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"index",'action'=>'province-list'),null,true); ?>';"/>
											<input type="submit" value="<?php echo $tr->translate("GO_EDIT");?>" label="<?php echo $tr->translate("GO_EDIT");?>" id="submitButton" dojoType="dijit.form.Button" 
											 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("add_province").submit();"/>
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
	</table>	
</form>