<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SRMS_ROOM_LIST"));
?>	
<?php $frm =  $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'global','controller'=>'index','action'=>'room-list')); ?>" dojoType="dijit.form.Form" method="post">
<div dojoType="dijit.layout.AccordionPane">
   <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   <?php echo $frm->getElement("title");?>
   <?php echo $frm->getElement('status_search');?>
   <input class="right"  type="button"​ id="add-room" Iconclass="dijitIconNewTask" value="<?php echo $tr->translate("ADD_CLASSNAME_NAME");?>" label="<?php echo $tr->translate("ADD_NEW");?>" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $this->url(array('module'=>"global",'controller'=>"index",'action'=>'add-room'),null,true); ?>';"/>
</div>
<?php echo $this->list;?>
</form>

