<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_SCHOOL')); 
?>
<?php  $school= $this->frm_school;?>
<form id="add_school" action="<?php echo $this->url(array('module'=>'global','controller'=>'highschool','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                  if(dijit.byId('record_row').get('value')==''){
				         alert('Please Select subject must be record!');
                         return false;
                 }



				return true;
			}else {
				return false;
			}
</script>
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_SCHOOL_NAME");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%">
									<tr>
										<td><?php echo $tr->translate("SCHOOLNAME")?></td>
										<td><?php echo $school->getElement("schoolname");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("KH_school")?></td>
										<td><?php echo $school->getElement("province");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("STATUS")?></td>
										<td>
										<?php echo $school->getElement("status");?>
										</td>
									</tr>
									<tr>
										<td colspan="2" align="center">
											<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>