<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_SCHOOL')); 
?>
<?php  $school= $this->frm_school;?>
<form id="add_school" action="<?php echo $this->url(array('module'=>'global','controller'=>'highschool','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_SCHOOL_NAME");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%">
									<tr>
										<td>
										<?php echo $school->getElement("id")?>
										<?php echo $tr->translate("SCHOOLNAME")?></td>
										<td><?php echo $school->getElement("schoolname");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("KH_school")?></td>
										<td><?php echo $school->getElement("province");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("STATUS")?></td>
										<td>
										<?php echo $school->getElement("status");?>
										</td>
									</tr>
									<tr>
										<td colspan="2" align="center">
											<input type="submit" value="<?php echo $tr->translate("GO_SAVE");?>" label="<?php echo $tr->translate("GO_SAVE");?>" id="submitButton" dojoType="dijit.form.Button" 
											 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("add_school").submit();"/>
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>