<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report page'); 
	$this->headTitle('SRMS | Report List Of Item'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<form  id='rpt_list_of_item' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'report','action'=>'rpt-rpt-list-of-item')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div style="width:100%; background:none repeat scroll 0% 0% rgba(234, 255, 253, 1);">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
				<fieldset style="background: none;height: 600px;overflow: scroll;overflow-x:hidden;">
							<legend align="center" ><strong><?php echo $tr->translate("");?></strong></legend>
							<table style="width:30cm;background:#fff; margin: 0 auto; border: 1px dotted #ccc;">
								<tr style="font-size: 13px;">
									<td colspan="2"></td>
									<td align="left">
										<strong>សាកលវិទ្យាល័យ​​​ វេស្ទើន</strong><br />
										<strong>western University</strong><br />
									</td>
							
									<td align="right">
										<strong><u>Free List of Item</u></strong><br />
										<strong>2013</strong><br />
										<strong>Effective date:</strong><br /><br />
										<strong>Exchange Rate(Riel/US$)=4100</strong><br />
									</td>
								</tr>
								<tr>
									<tr>
									<td colspan="5">
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<tr style="font-size:12px; height: 30px;" align="center" >
												<th rowspan="2">N<sup>o</sup></th>
												<th rowspan="2">Item Description</th>
												<th colspan="2">1</th>
												<th colspan="2">2</th>
												<th colspan="2">3</th>	
									
											</tr>
											<tr align="center"​​>
												<th colspan="2"><small>Price R(Riel)</small></th>	
												
												<th colspan="2"><small>Price $(1)</small></th>
													
												<th colspan="2"><small>Price $(2)</small></th>
												
											</tr>
											<?php for ($i=1;$i<25;$i++){?>
											<tr style="font-size:12px;height:30px;"​ align="center">
												<td ><?php echo $i;?></td>
												<td >Certificate: Ass. & BA with frame</td>
												<td colspan="2">R8,000</td>
												<td colspan="2">$2</td>
												<td colspan="2"></td>
											</tr>
											<?php }?>
										</table>
									</td>
								
								</tr>
							</table>
				</fieldset>		
				</td>
			</tr>
		</table>
	</div>	
</form>
