<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Receivable'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<style>
#footer{display: none;}
</style>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'report','action'=>'rpt-final-exams')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div style="width:100%; background:none repeat scroll 0% 0% rgba(234, 255, 253, 1);">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
				<fieldset style="background: none;height: 600px;overflow: scroll;overflow-x:hidden;">
							<legend align="center" ><strong><?php echo $tr->translate("REPORT_STUDENT_RECIEVABLE");?></strong></legend>
								
							<table style="width:30cm;background:#fff; margin: 0 auto; border: 1px dotted #ccc;">
								<tr style="font-size: 13px;">
									<td align="center">
										<img src="<?php echo $this->baseUrl();?>/images/logo.png" height="85px;" />
									</td>
									<td></td>
									<td><br />
										<label>Note: </label><br />
										<label>BAHL=Arts,Humanities&Language</label><br />
										<label>B-SS=Social Science</label><br />
										<label>B-BA = Business Administration</label>
									</td>
								</tr>
								<tr>
									<td width="25%" align="center">
										<strong>សាកលវិទ្យាល័យ វេស្ទើន</strong><br />
										<strong>WESTERN UNIVERSITY</strong><br /><br ><br >
									</td>
									<td align="center">
										<strong></strong><br >
									</td>
									<td width="25%"></td>
								</tr>
								<tr>
									<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>

									<style type="text/css">
body{font-family: "Times New Roman",Arial; }
table{ border-collapse:collapse; margin:0 auto;
border:0px;
border-style:solid; border-color:#000; }
.padd tr td{ padding:0px 2px 0px 2px; font-size:10px; text-align:center}
.padd tr th{ padding:5px 2px 5px 2px; font-size:10px; text-align:center }
tr.b_right td{border-right:1px solid #000; }
tr.b_right th{border-right:1px solid #000} 
</style>

<table class="padd" width="99%" border="1" align="center">
  <tr >
    <th colspan="3"  width="25%">Quarter II&amp;IV</th>
    <th rowspan="2" >Paid Amount</th>
    <th rowspan="2" >Balance forward from previous</th>
    <th rowspan="2" >Balance Due</th>
    <th rowspan="2" width="49%" >References</th>
  </tr>
  <tr>
    <td>May</td>
    <td>Jun</td>
    <td>July</td>
    
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td style="text-align:right">&nbsp;</td>
    <td><div align="right">140.00</div></td>
    <td>&nbsp;</td>
    <td ><b></b></td>
    <td style="text-align:left">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td style="text-align:right">&nbsp;</td>
    <td><div align="right">215.00</div></td>
    <td><b></b></td>
    <td>&nbsp;</td>
    <td style="text-align:left"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td style="text-align:right">&nbsp;</td>
    <td><div align="right">105.00</div></td>
    <td>&nbsp;</td>
    <td><b></b></td>
    <td style="text-align:left">200/Y from Mr.TLR, 4year</td>
  </tr>
  <tr>
    <td height="23">&nbsp;</td>
    <td>&nbsp;</td>
    <td style="text-align:right">&nbsp;</td>
    <td><div align="right">120.00</div></td>
    <td>(60.00) </td>
    <td><b>120.00 </b></td>
    <td style="text-align:left">300/Y from Mr.TLR paid monthly=30$, over paid   .................................................</td>
  </tr>
  <tr>
    <td height="23">&nbsp;</td>
    <td>&nbsp;</td>
    <td style="text-align:right">&nbsp;</td>
    <td><div align="right">140.00</div></td>
    <td>&nbsp;</td>
    <td><b></b></td>
    <td style="text-align:left"></td>
  </tr>
</table>
									
									
									
									
									</td>
								</tr>
							</table>
				</fieldset>		
				</td>
			</tr>
		</table>
	</div>	
</form>

