<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Report Tuition Fee'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'report','action'=>'rpt-tuition-fee')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div style="width:100%; background:none repeat scroll 0% 0% rgba(234, 255, 253, 1);">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
				<fieldset style="background: none;height: 600px;overflow: scroll;overflow-x:hidden;">
							<legend align="center" ><strong><?php echo $tr->translate("");?></strong></legend>
							<table style="width:30cm;background:#fff; margin: 0 auto; border: 1px dotted #ccc;">
								<tr style="font-size: 13px;">
									
									<td align="left" >
										<strong>សាកលវិទ្យាល័យ វេស្ទើន</strong><br />
										<strong>Western University</strong><br />
									</td>
									<td align="right" width="20%">
										<strong><u>School Tuition Fee</u></strong><br />
										<strong>2013</strong><br />
										<small>Effective date:</small><br />
									</td>
								</tr>
								<tr>
									<td><br ><br ><br ></td>
								</tr>
								<tr>
									<td colspan="3">
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th rowspan="2">S3</th>
												<th rowspan="2">Course Title</th>
												<th colspan="2">1</th>
												<th colspan="2">2</th>
												<th colspan="2">3</th>	
									
											</tr>
											<tr align="center"​​>
												<th colspan="2" width="20%"><small>Fee</small></th>	
												
												<th colspan="2"><small>2Terms</small></th>
													
												<th colspan="2"><small>3Terms</small></th>
												
											</tr>
										</table>
										</td>
										</tr>
										<?php for ($j=1;$j<3;$j++){?>
									<tr style="font-size: 13px;">
									
										<td align="left" style="padding-left:5px;">
													<strong>General Englidh Programm(GEP)</strong><br />
												</td>
												<td align="right" width="20%" style="padding-right:5px;">
													<strong>Full Time(120hrs)</strong><br />
												</td>			
									</tr>
									
									<tr>
										<td colspan="3">		
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<style> td{padding:0 3px; }</style>
											<?php for ($i=1;$i<10;$i++){?>
											<tr style="font-size:11px;height:30px;"​ align="center">
												<td width="6.6%"><?php echo $i;?></td>
												<td width="32.3%">Children(1,2,3)</td>
												<td width="20%">$85.00</td>
												<td width="20.8%">$155.00</td>
												<td ></td>
											</tr>
											<?php }?>		
										</table>	
									</td>
								</tr>
								<?php }?>
							</table>
				</fieldset>		
				</td>
			</tr>
		</table>
	</div>	
</form>
