<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Receivable'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<style>
#footer{display: none;}
</style>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'report','action'=>'rpt-final-exams')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div style="width:100%; background:none repeat scroll 0% 0% rgba(234, 255, 253, 1);">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
				<fieldset style="background: none;height: 600px;overflow: scroll;overflow-x:hidden;">
							<legend align="center" ><strong><?php echo $tr->translate("REPORT_STUDENT_RECIEVABLE");?></strong></legend>
							<table style="width:30cm;background:#fff; margin: 0 auto; border: 1px dotted #ccc;">
								<tr style="font-size: 13px;">
									<td align="center">
										<img src="<?php echo $this->baseUrl();?>/images/logo.png" height="85px;" />
									</td>
									<td></td>
									<td><br />
										<label>Note: </label><br />
										<label>BAHL=Arts,Humanities&Language</label><br />
										<label>B-SS=Social Science</label><br />
										<label>B-BA = Business Administration</label>
									</td>
								</tr>
								<tr>
									<td width="25%" align="center">
										<strong>សាកលវិទ្យាល័យ វេស្ទើន</strong><br />
										<strong>WESTERN UNIVERSITY</strong><br /><br ><br >
									</td>
									<td align="center">
										<strong><u>Term 5 start from 14-OCT-13 to 12-DEC-2013</u></strong><br >
									</td>
									<td width="25%"></td>
								</tr>
								<tr>
									<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
body{font-family: "Times New Roman",Arial; }
table{ border-collapse:collapse; margin:0 auto;
border:0px;
border-style:solid; border-color:#000; }
.padd tr td{ padding:0px 2px 0px 2px; font-size:9px; text-align:center}
.padd tr th{ padding:5px 2px 5px 2px; font-size:9px; background-color: #ccc; }
tr.b_right td{border-right:1px solid #000; }
tr.b_right th{border-right:1px solid #000} 
</style>

<table class="padd" width="99%" border="1" align="center">
  <tr>
    <th >No</th>
    <th >ID No.</th>
    <th >Name of student</th>
    <th >Sex</th>
    <th >DOB</th>
    <th >Tel.</th>
    <th>Student ID</th>
    <th >Session</th>
    <th >Level</th>
    <th >Pay for(Term)</th>
    <th >Group</th>
    <th >Class Room</th>
    <th>Staus</th>
    <th >Type of Pmnt</th>
    <th >Amount</th>
    <th>Dis.%</th>
    <th >Day Deduction</th>
    <th >Net Tuition</th>
    <th >Paid Amount</th>
    <th >Balance forward from previous</th>
    <th >A/R Balance</th>
    <th>Reference</th>
  </tr>
  <tr>
    <td>1</td>
    <td>&nbsp;</td>
    <td style="text-align:left">Heng Sirimongkul</td>
    <td>M</td>
    <td>12-Sep-2004</td>
    <td>012121212</td>
    <td>GEP-2725</td>
    <td>FT</td>
    <td>Begginer 2</td>
    <td>5</td>
    <td>A</td>
    <td>Columbia</td>
    <td>Active</td>
    <td>T</td>
    <td>85.00</td>
    <td>10%</td>
    <td>&nbsp;</td>
    <td>76.5</td>
    <td>76.5</td>
    <td>&nbsp;</td>
    <td>-</td>
    <td>Dis. 10% for Second Child</td>
  </tr>
  <tr>
    <td>2</td>
    <td>&nbsp;</td>
    <td style="text-align:left">Heng Sirivathanak</td>
    <td>M</td>
    <td>12-Sep-2003</td>
    <td>034343944/099343433</td>
    <td>GEP-2724</td>
    <td>FT</td>
    <td>Begginer 2</td>
    <td>5</td>
    <td>A</td>
    <td>Columbia</td>
    <td>Active</td>
    <td>T</td>
    <td>85.00</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>85.00</td>
    <td>&nbsp;</td>
    <td>-</td>
    <td>Dis. 25% for Second Child</td>
  </tr>
  <tr>
    <td>3</td>
    <td>&nbsp;</td>
    <td style="text-align:left">Chantbol Vattanak</td>
    <td>M</td>
    <td>12-Sep-2001</td>
    <td>067657657</td>
    <td>GEP-2726</td>
    <td>FT</td>
    <td>Begginer 2</td>
    <td>5</td>
    <td>M</td>
    <td>Columbia</td>
    <td>Active</td>
    <td>T</td>
    <td>85.00</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>85.00</td>
    <td>&nbsp;</td>
    <td>-</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>4</td>
    <td>&nbsp;</td>
    <td style="text-align:left">Ouk Heng Rathanak</td>
    <td>M</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>GEP-2728</td>
    <td>FT</td>
    <td>Begginer 2</td>
    <td>5</td>
    <td>A</td>
    <td>Columbia</td>
    <td>Active</td>
    <td>T</td>
    <td>85.00</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>-</td>
    <td>&nbsp;</td>
    <td>85.50</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>5</td>
    <td>&nbsp;</td>
    <td style="text-align:left">Chea Layheng</td>
    <td>M</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>GEP-2726</td>
    <td>FT</td>
    <td>Begginer 2</td>
    <td>5</td>
    <td>A</td>
    <td>Columbia</td>
    <td>Active</td>
    <td>T</td>
    <td>85.00</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>85.00</td>
    <td>&nbsp;</td>
    <td>-</td>
    <td>&nbsp;</td>
  </tr>
</table>
									
									</td>
								</tr>
							</table>
				</fieldset>		
				</td>
			</tr>
		</table>
	</div>	
</form>

