<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	
	$session_user=new Zend_Session_Namespace('auth');
	$username = $session_user->first_name;
	$them_style =  $session_user->theme_style;
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<script src="<?php echo $base_url;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>/js/dojo-1.6.1/dijit/themes/tundra/tundra.css"/>
	<!--  <link rel="stylesheet" type="text/css" href="<?php //echo $base_url;?>/js/dojo-1.6.1/dijit/themes/claro/claro.css"/>-->
	<!--  <link rel="stylesheet" type="text/css" href="<?php //echo $base_url;?>/js/dojo-1.6.1/dijit/themes/tundra/tundra.css"/>-->
	
	<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>/js/dojo-1.6.1/dojox/grid/resources/tundraGrid.css"/>
	<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
	<script src="<?php echo $base_url;?>js/pdbs_js.js"  type="text/javascript"></script>
	<link rel="stylesheet" href="<?php echo $base_url;?>css/template.css"/>
	<link href="<?php echo $base_url;?>/cssmenu/template.css" media="screen" rel="stylesheet" type="text/css">
	<!-- table  -->
	<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"> </script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.pager.js"> </script>

	<link rel="shortcut icon" href="<?php echo $base_url;?>images/icon.ico" type="image/x-icon"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<style type="text/css">
*{ padding:0;margin:0;}
    html, body { width: 100%; height: 100%; margin: 0; }
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.fullside{ width:98%; height: 30px;}
		.full{ width:100%;}
		body, html {font-size:98%; font-family:'Khmer OS Battambang'}
        /*body, html { font-family:helvetica,arial,sans-serif; font-size:95%; }*/
		*{ padding: 0; margin: 0;}
		fieldset{ font-family: inherit;}
	</style>	
</head>
<script>
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require('dijit.form.Form');
dojo.require('dijit.form.FilteringSelect');	
dojo.require('dijit.form.Button');
dojo.require('dijit.form.NumberTextBox');
dojo.require("dijit.form.CheckBox");     
dojo.require("dojo.number");
dojo.require('dojox.form.BusyButton');
dojo.require("dijit.form.RadioButton");
dojo.require("dijit.Dialog");

dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.layout.AccordionContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.parser");

           dojo.addOnLoad(function() {
            	var url = document.URL;
            	var module =url.split('public/')[1];
            	id = module.split("/")
            	try
          	  	{
            		dojo.addClass(id[0],"style1");
            		if(id.length>1){
            			var tmp = url.split("/");
            			id=tmp.pop()
            			dojo.addClass(id,"style1");
                	}
          	  	}
          		catch(err)
          		{
    		         if(id=="agent"){
     		             dojo.addClass("agents","style1");
        		     }
          	  	}
         		 if (document.pub) {
                     document.pub();
                 }
            });

</script>
    <?php $class='tundra';?>
    <!-- <body class="soria">
    <body class="soria"> -->
    <body class="<?php echo $class;?>">
     <table width="100%">
                <tr>
                	<td colspan="2" valign="top" style="position: fixed;width: 100%; z-index: 1;top: 0;background:rgb(243, 241, 241) none repeat scroll 0% 0%" >
                	
            <!-- <img src='<?php //echo $base_url;?>images/logo.png' height="100px"/ > --> 
            <?php 
        	?>
				
             <?php echo $this->render('header.phtml')?>
            			    <p style="font-size:13px !important; ">
						              <span style="padding-left: 3px;padding-right: 3px;float: left; font-weight:600;"><?php echo $tr->translate("USING_BY");?><a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>"><?php echo $username;?></a></span>  
							<a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>"> | <?php echo $tr->translate("SIGN_OUT");?></a>
			                 <?php if($action=='index' AND $module!='report' AND $module!='home'){?>
			                 <a class='add-link' style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'add'),null,true); ?>"><?php echo $tr->translate('ADD');?></a>
							<?php }elseif($action=='add' OR $action=='edit' OR $module=='report'){?>
							 <span style="padding-left: 3px;padding-right: 3px; float: right; font-weight:600;"><a class='add-link' href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><?php echo $tr->translate('GO_BACK');?></a></span>
							<?php }?>
							</p>
                      </td>
                 </tr>
                 <tr>
                	<td colspan="2" height="70px;"></td>
                </tr>
                <tr>
                	<td valign="top" <?php if($module!='home') echo'width="220px"';  ?> >
			             <?php if($module!='home'){?>
			             <?php echo $this->render('menuleft.phtml')?>
			             <?php }?>
                     </td>
                     <td valign="top">
            			<?php if($module=='report' AND $action!='index'){?>
							<div class="menureport">
								<ul>
									<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
									<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
									<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
								</ul>
							</div>
							<div style="clear:both;"></div>
							<?php }?>
            			<?php echo $this->layout()->content; ?>
            			<?php //echo $this->layout()->content; 
			               	if($module=='report' AND $action!='rpt-paymentschedules'){
			                ?>
		                <?php }?>
            		</td>
                </tr>
                <?php //echo $this->layout()->content;  ?>
            </table>
               <!--  <ul>
					<li><?php //echo $tr->translate("COPY_RIGHT")." &copy; ".$tr->translate("COPY_RIGHT_BY");?></li>
					<li><?php //echo $tr->translate("VERSION");?></li>
					<li><?php //echo $tr->translate("POWER_BY");?></li>
				</ul> -->
    </body>
</html>
<script type="text/javascript">
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
</script>