<?php
	$this->headTitle('Currency Smart | Profile edit page'); 
	echo $this->headTitle();
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>
<form action="<?php echo $this->url(array('module'=>'profile','controller'=>'index','action'=>'')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}

			return false;
	</script>
	<table cellspacing="20" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend><strong>ព័ត៌មាន​ ក្រុមហ៊ុន</strong></legend>
					<table cellspacing="20" width="100%">
						<tr>
							<td align="center" valign="top">
								<table width="100%">
									<tr>
										<td>ពិស្ដាជាខ្មែរ</td>
										<td>
											<input type="text" required="true" name="rpt-transfer-business-meaning-kh" id="rpt-transfer-business-meaning-kh" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->data['rpt-transfer-business-meaning-kh'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពិស្ដាជាខ្មែរ!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>ពិស្ដាជាអង់គ្លេស</td>							
										<td>
											<input type="text" name="rpt-transfer-business-meaning-eng" id="rpt-transfer-business-meaning-eng"
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->data['rpt-transfer-business-meaning-eng'];?>" class='fullside'/>
										</td>
									</tr>
								</table>
							</td>
							<td valign="top" align="center">
								<table  width="100%">
									<tr>
										<td width="20%">អាសយដ្ឋាន</td>
										<td width="80%">
											<input type="text" required="true" name="rpt-transfer-location-adr-kh" id="rpt-transfer-location-adr-kh" placeholder="អាសយដ្ឋាន" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->data['rpt-transfer-location-adr-kh'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ អាសយដ្ឋាន!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>លេខទូរស័ព្ទ</td>
										<td>
											<input type="text" required="true" name="bracnch-tel" id="bracnch-tel" placeholder="លេខទូរស័ព្ទ" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->data['bracnch-tel'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ លេខទូរស័ព្ទ!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>អក្សរ​រត់​ទំព័រចាប់​ផ្ដើម​</td>							
										<td>
											<input type="text" required="true" name="marquee-word" id="marquee-word" placeholder="អក្សរ​រត់​ទំព័រចាប់​ផ្ដើម​" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->data['marquee-word'];?>"
											 missingMessage="អ្នក​ភ្លេច​បំពេញ​ លេខទូរស័ព្ទ!" class='fullside'/>
										</td>
									</tr>	
								</table>
							</td>
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>
	
</form>