<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_ROOM')); 
?>	

<?php  $frm_subject_exam= $this->frm_;?>
<form  id='add_subject_exam' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'student','action'=>'add-subject-exam')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="40%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("ADD_SUBJECT_EXAM_NAME");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td style="width: 100px"><?php echo $tr->translate("SUBJECT_EXAM")?></td>
							<td><?php  echo $frm_subject_exam->getElement('subject_exam_name');?></td>
						</tr>
						<tr>
							<td style="width: 100px"><?php echo $tr->translate("DATE")?></td>
							<td><?php  echo $frm_subject_exam->getElement('date');?></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $frm_subject_exam->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									 iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"index",'action'=>''),null,true); ?>';" />
								<input type="submit"  label="<?php echo $tr->translate('GO_SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("add_subject_exam").submit();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
