<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Add Room'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.form.CheckBox");     
	dojo.require("dojo.number");
	dojo.require('dojox.form.BusyButton');
	dojo.require("dijit.Dialog");

</script>
<style>
select{ width:100%;}
//dt{display:none;}
</style>
<?php  $classname= $this->frm_classname;?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'index','action'=>'add-room')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="40%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("ADD_CLASSNAME_NAME");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td style="width: 100px"><?php echo $tr->translate("CLASSNAME")?></td>
							<td><?php  echo $classname->getElement('classname');?></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $classname->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>