<?php 
	$frm_student = $this->frm_student;
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
	<script>
		dojo.require("dojo.data.ObjectStore");
		dojo.require("dojo.data.ItemFileWriteStore");  
		dojo.require("dojo.store.Memory");
		dojo.require("dojo.data.ObjectStore");
		
		var major_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		var situation_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->situation));?> );
		var compo_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->compo));?> );
		var highschool_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		
		dojo.ready(function(){
		new dijit.form.FilteringSelect({
	        store: major_store,
	        autoComplete: true,                        
	        required: true,
	        id: "major",
	        name: "major",           
	        class: 'fullside',            
	        missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
	        onChange: function() {  
	        	major_id = dijit.byId('major').get('value');
	        	if(major_id==-1){
	        		fac_id = dijit.byId('dept').get('value');
		        	dijit.byId('facultyid').attr('value',fac_id);
		        	dijit.byId('lbl_faculty').attr('value',dijit.byId('dept').attr('displayedValue'));
					dijit.byId('pop_major').show();
			     }           
	        }
	    }, "major");

		new dijit.form.FilteringSelect({
		        store: situation_store,
		        autoComplete: true,                        
		        required: true,
		        id: "situation",
		        name: "situation",           
		        class: 'fullside',            
		        missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
		        onChange: function() {  
		        	situation_id = dijit.byId('situation').get('value');
		        	if(situation_id==-1){
						dijit.byId('pop_situation').show();
				     }           
		        }
		    }, "situation");

		new dijit.form.FilteringSelect({
	        store: compo_store,
	        autoComplete: true,                        
	        required: true,
	        id: "composition",
	        name: "composition",           
	        class: 'fullside',            
	        missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
	        onChange: function() {  
	        	composition = dijit.byId('composition').get('value');
	        	if(composition==-1){
		        	dijit.byId('pop_composition').show();
			     }           
	        }
	    }, "composition");
		new dijit.form.FilteringSelect({
	        store: highschool_store,
	        autoComplete: true,                     
	        id: "from_school",
	        name: "from_school",           
	        class: 'fullside',            
	        missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
	        onChange: function() {  
	        	//composition = dijit.byId('composition').get('value');
	        	//if(composition==-1){
		        //	dijit.byId('pop_composition').show();
			    // }           
	        }
	    }, "from_school");

		}); 
		
   </script>
		<form id="add_student" dojoType="dijit.form.Form" method="post">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
		</script>
				<table width="100%">
					<tr>
						<td>
						 <div id="mainTabContainer" style="width: 1150px;height: 350px;" dojoType="dijit.layout.TabContainer" region="center" width="1000px !importand" >
					      <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("STUDENT_INFO");?>" selected="true">
					      	<table cellspacing="8" style="margin:0 auto;" width="100%">
					      		<tr>
					      			<td  title="ឈ្មោះជាភាសារខ្មែរ"><?php echo $tr->translate("NAME_KH");?>*</td>
									<td><?php echo $frm_student->getElement('kh_name');?></td>
									<td  title="ឈ្មោះជាភាសារអង់គ្លេស"><?php echo $tr->translate("NAME_EN");?>*</td>
									<td><?php echo $frm_student->getElement('en_name');?></td>
									<td title="បញ្ជូលភេទនិស្សិត"><?php echo $tr->translate("SEX");?>*</td>
									<td><?php echo $frm_student->getElement('sex');?></td>
					      		</tr>
					      		<tr>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("DOB");?>*</td>
									<td><?php echo $frm_student->getElement('dob');?></td>
									<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("PHONE");?>*</td>
									<td><?php echo $frm_student->getElement('phone');?></td>
									<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("ADDRESS");?>*</td>
									<td><?php echo $frm_student->getElement('address');?></td>
					      		</tr>
					      		<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;">ព័ត៏មានសិក្សានៅមហាវិទ្យាល័យ</td>
					      		</tr>
					      		<tr>
					      			<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("STUDENT_ID");?>*</td>
									<td><?php echo $frm_student->getElement('stu_card');?></td>
									<td><?php echo $tr->translate("DEGREE");?>*</td>
									<td><?php echo $frm_student->getElement('degree');?></td>
									<td><?php echo $tr->translate("BATCH");?>*</td>
									<td><?php echo $frm_student->getElement('batch');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("FACULTIES");?>*</td>
									<td><?php echo $frm_student->getElement('dept');?></td>
									<td><?php echo $tr->translate("MAJOR_C");?>*</td>
									<td><input id="major" /><?php //echo $frm_student->getElement('major');?></td>
									<td><?php echo $tr->translate("YEAR");?>*</td>
									<td><?php echo $frm_student->getElement('year');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("SEMESTER");?>*</td>
									<td><?php echo $frm_student->getElement('semester');?></td>
									<td><?php echo $tr->translate("SESSION");?>*</td>
									<td><?php echo $frm_student->getElement('session');?></td>
									<td colspan="4"></td>
								</tr>
					      	</table>
					      </div><!-- end tab 1 -->
					      <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("STUDNET_EDUCATION");?>" selected="false">
					     	<table width="100%" style="margin:0 auto;" cellspacing="8">
					      		<tr>
					      			<td width="12%"><?php echo $tr->translate("FATHER_TEL");?>*</td>
									<td><?php echo $frm_student->getElement('father_phone');?></td>
									<td ><?php echo $tr->translate("MOTHER_TEL");?>*</td>
									<td><?php echo $frm_student->getElement('mother_phone');?></td>
									<td><?php echo $tr->translate("SITUATION");?>*</td>
									<td><input id="situation" /><?php //echo $frm_student->getElement('situation');?></td>
					      		</tr>
					      		<tr>
									<td><?php echo $tr->translate("BACC_EXAME");?>*</td>
									<td><?php echo $frm_student->getElement('finish_bacc');?></td>
									<td><?php echo $tr->translate("CERTIFICATE_CODE");?>*</td>
									<td><?php echo $frm_student->getElement('certificate_code');?></td>
									<td><?php echo $tr->translate("SCROE");?>*</td>
									<td><?php echo $frm_student->getElement('bacc_score');?></td>
					      		</tr>
					      		<tr>
					      			<td ><?php echo $tr->translate("MENTION");?>*</td>
									<td><?php echo $frm_student->getElement('mention');?></td>
									<td ><?php echo $tr->translate("អនាគតដ្ឋាន");?>*</td>
									<td><?php echo $frm_student->getElement('school_location');?></td>
									<td ><?php echo $tr->translate("FROM_SCHOOL");?>*</td>
									<td><input id="from_school" /><?php //echo $frm_student->getElement('from_school');?></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("POB");?>*</td>
									<td><?php echo $frm_student->getElement('pob');?></td>
									<td><?php echo $tr->translate("ADD_STUDENT");?>*</td>
									<td><?php echo $frm_student->getElement('student_add');?></td>
									<td ><?php echo $tr->translate("COMPOSITION");?>*</td>
									<td><input id="composition" /><?php //echo $frm_student->getElement('composition');?></td>
					      		</tr>
					      		<tr>
					      			<td ><?php echo $tr->translate("STUDNET_FROM");?>*</td>
									<td><?php echo $frm_student->getElement('student_from');?></td>
					      			<td ><?php echo $tr->translate("REMARK");?></td>
									<td><?php echo $frm_student->getElement('remark');?></td>
					      			<td ><?php echo $tr->translate("STATUS");?>*</td>
									<td><?php echo $frm_student->getElement('status');?></td>
					      		</tr>
					      	</table>
					      </div>
					   </div>
					   </td>
					</tr>
					<tr>
						<td align="center">
					   				<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
					   	</td>
					  </tr>
					  </table>
					</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_major" >
		<form id='frm_major' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>មហាវិទ្យាល័យ</td>
				<td><input dojoType="dijit.form.TextBox"  id="facultyid" name="facultyid" value="" type="hidden">
				<input dojoType="dijit.form.TextBox" readonly="readonly"  id="lbl_faculty" name="lbl_faculty" value="" type="text"></td>
				</td>
			</tr>
			
			
			<tr>
				<td>ជំនាញ/EN</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="full height-text" id="major_en" name="major_en" value="" type="text"></td>
			</tr>
			<tr>
				<td>ជំនាញ/KH</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="full height-text" id="major_kh" name="major_kh" value="" type="text"></td>
			</tr>
			<tr>
				<td>អក្សរកាត់</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" class=" fullside height-text" missingMessage="ភ្លេច​បំពេញ​ពាក្យកាត់!" id="shortcut" name="shortcut" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewMajor();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_situation" >
		<form id='frm_situation' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>វណ្ណៈក្នុងគ្រួសារ</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_situation" name="txt_situation" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addsituation();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_composition" >
		<form id='frm_composition' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>សមាសភាពនិស្សិត</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="occu_name" name="occu_name" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addcomposition();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>


<script>
function printSave(){
	alert(1);
	dijit.byId("edit-student").submit();
}

var url_major = '<?php echo $this->url(array('module'=>'global','controller'=>'major','action'=>'addmajor')); ?>';
function addNewMajor(){
	if(dijit.byId('frm_major').validate()){
		dojo.xhrPost({
			url:url_major,
			form: dojo.byId("frm_major"),
			handleAs:"json",
			load: function(data) {
				var majorItem = {					
						id: data,
					    name: dijit.byId('major_en').get('value')+' - '+dijit.byId('major_kh').get('value')
				};			
				addDataToSelectbox(dijit.byId('major'), major_store, majorItem, data);
				dijit.byId('frm_major').reset();
				dijit.byId("pop_major").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var url_situation = '<?php echo $this->url(array('module'=>'global','controller'=>'situation','action'=>'addsituation')); ?>';
function addsituation(){
	if(dijit.byId('frm_situation').validate()){
		dojo.xhrPost({
			url:url_situation,
			form: dojo.byId("frm_situation"),
			handleAs:"json",
			load: function(data) {
				var situItem = {					
						id: data,
					    name: dijit.byId('txt_situation').get('value')
				};			
				addDataToSelectbox(dijit.byId('situation'), situation_store, situItem, data);
				dijit.byId('frm_situation').reset();
				dijit.byId("pop_situation").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var url_composition = '<?php echo $this->url(array('module'=>'global','controller'=>'occupation','action'=>'addcomposition')); ?>';
function addcomposition(){
	if(dijit.byId('frm_composition').validate()){
		dojo.xhrPost({
			url:url_composition,
			form: dojo.byId("frm_composition"),
			handleAs:"json",
			load: function(data) {
				var compoItem = {					
						id: data,
					    name: dijit.byId('occu_name').get('value')
				};
				addDataToSelectbox(dijit.byId('composition'), compo_store, compoItem, data);
				dijit.byId('frm_composition').reset();
				dijit.byId("pop_composition").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var url_getmajor = '<?php echo $this->url(array('module'=>'foundation','controller'=>'index','action'=>'get-majors')); ?>';
function changeMajor(){
	dept_id = dijit.byId('dept').get('value');
			dojo.xhrPost({
			    url: url_getmajor,			    
			    content : { 
				    'dept_id':  dept_id	    
				},
				handleAs:"json", 
			    load: function(response) {
			    	major_store  = getDataStorefromJSON('id','name', response);
					dijit.byId('major').set('store',major_store); 					    		    					    		    	
			    },
			    error: function(err) {
			    	 alert(err);
			        
			    }
			});
}

function CheckBaccCode(){
	alert('check code of bacc');
}
var url_getschool = '<?php echo $this->url(array('module'=>'foundation','controller'=>'index','action'=>'get-school')); ?>';
function filterSchool(){
		dojo.xhrPost({
			url:url_getschool,
			  content : { 
				    'province_id' :  dijit.byId('school_location').get('value')	    
				},
			handleAs:"json",
			load: function(response) {
				//alert(data);
				highschool_store  = getDataStorefromJSON('id','name', response);
				dijit.byId('from_school').set('store',highschool_store); 		
// 				var schoolItem = {					
// 						id: -1,
// 						province_id: dijit.byId('school_location').get('value'),
// 					    name: 'បន្ថែម​អ្នក​ទទួល​ថ្មី'
// 				};
// 				addDataToSelectbox(dijit.byId('from_school'), highschool_store, schoolItem, -1);
// 				dijit.byId('from_school').query.province_id =dijit.byId('school_location').get('value');
			},
			error: function(err) {
				alert(err);
			}
		});
	
	
}
</script>
