<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SRMS_TEACHER"));
?>	
<?php $frm =  $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	<?php echo $frm->getElement('subjec_name');?>
	<?php echo $frm->getElement("title");?>
	<?php echo $frm->getElement('status_search');?>
</form>
<?php echo $this->list;?>