<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle(); 
	echo $this->headTitle($tr->translate("SRMS_DEPT"));
	$url = Application_Form_FrmMessage::getUrl("/global/index/index?us_id=");
?>	

<style>
	#grid{
		margin: 0 auto;
	}
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px; 		
	}
	.height-text{height:30px; min-width: 350px;}
</style>
<script>
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojox.grid.DataGrid");	
dojo.require("dijit.Dialog");
	
	dojo.ready(function(){
		
		//Creat data fror show			
		loadData(<?php print_r($this->dept_list);?>);
		dojo.connect(grid, "onRowClick", grid, function(evt){
			var idx = evt.rowIndex,
				item = this.getItem(idx);

			window.location = '<?php echo $url;?>' + this.store.getValue(item, "id");
		});
	});

	function loadData(data){			
		// create an object store
		var objectStore = new dojo.store.Memory({
		       data: data		       
		 });
		
		//load data into data grid
		grid = new dojox.grid.DataGrid({						
			store: dojo.data.ObjectStore({objectStore: objectStore}),	
			autoHeight: true, 		
			structure: [
				{ name: "<?php echo $tr->translate("No_C");?>", field: "num", width: "40px", cellStyles: "text-align: center;" },
				{ name: "id", field: "id", hidden: "true" },
				{ name: "<?php echo $tr->translate("DEPT_NAME_C");?>", field: "room_name", width: "auto" },
				{ name: "<?php echo $tr->translate("MODIFY_DATE");?>", field: "modify_date", width: "auto" },
				{ name: "<?php echo $tr->translate("STATUS_C");?>", field: "is_active", width: "auto" },
				{ name: "<?php echo $tr->translate("BY_USER_C");?>", field: "user_name", width: "auto" }					
			]
		}, "grid");
		grid.startup();
	}
	
</script>

<form id="frmroom_list" name="frmroom_list" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'index','action'=>'room')); ?>" dojoType="dijit.form.Form" method="post">
<table class="full">	  	
	  <tr>
	    <td></td>
	    <td align="right">
	    	<select name="dept_name" id="dept_name"  onChange="document.frmdept_list.submit();" style=" height: 30px;" dojoType="dijit.form.FilteringSelect"> 
				<option value="-1" <?php if($this->active == -1) echo 'selected="selected"';?> ><?php echo $tr->translate("CHOOSE_DEPT"); ?></option> 
				<?php foreach ($this->activelist as $key => $at) : ?>
					<option value="<?php echo $key;?>" <?php if($key == $this->active) echo 'selected'?>><?php echo $at;?></option>
				<?php endforeach;?>	 
			</select>
			<select name="active" id="active"  onChange="document.frmdept_list.submit();" style=" height: 30px;" dojoType="dijit.form.FilteringSelect"> 
				<option value="-1" <?php if($this->active == -1) echo 'selected="selected"';?> ><?php echo $tr->translate("CHOOSE_STATUS"); ?></option> 
				<?php foreach ($this->activelist as $key => $at) : ?>
					<option value="<?php echo $key;?>" <?php if($key == $this->active) echo 'selected'?>><?php echo $at;?></option>
				<?php endforeach;?>	 
			</select>
		</td>			
	  </tr>	
	  <tr>
	  		<td colspan="2" align="right">&nbsp;<button dojoType="dijit.form.Button" onclick="showDialog();" showLabel="true" type="button" ><?php echo $tr->translate("ADD_NEW");?></button> </td>
	  </tr>
	  <tr>
		  	<td colspan="2">
		  		<div id="grid" ></div>
		  	</td>
	  </tr>	
	  <tr>
		  	<td>	  		
		  		<?php echo $this->result_row;?>
		  	</td>
		  	<td align="right" >
		  		<?php echo $this->rows_per_page;?>
		  	</td>
	  </tr>
	  <tr>
		  	<td colspan="2" align="center">
		  		<div id="navigetion" style="margin: 0 auto;"><?php echo $this->nevigation;?></div>
		  	</td>
	  </tr>	  
</table>
</form>
<?php $frm_dept = $this->add_dept;?>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" data-dojo-props="title:'<?php echo $tr->translate("ADD_DEPT");?>', onCancel:hideDialog" id="popup_dept" >
		<form id='frm_add_dept' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table>
			<tr>
				<td><?php echo $tr->translate("DEPT_NAME");?></td>
				<td>
					<?php echo $frm_dept->getElement("dpt_name");?></td>
			</tr>
			<tr>
				<td><?php echo $tr->translate("SHORTCUT");?></td>
				<td><?php echo $frm_dept->getElement("shortcut");?></td>
			</tr>
			<tr>
				<td><?php echo $tr->translate("STATUS");?></td>
				<td><?php echo $frm_dept->getElement("status");?></td>
			</tr>
			<tr>
				<td colspan="2" align="center"><br />
					<input type="button"  label="<?php echo $tr->translate("SAVE");?>" id="submitButton" 
					dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewDepartmen"/>
				<?php  //echo $frm_dept->getElement("save");?></td>
			</tr>
			<tr>
				<td colspan="2">&nbsp;</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<script>
function printSave(){		
	//if(dijit.byId('frm_add_tran').validate()) {
		/*if(dijit.byId('recieve_money').get('value') < dijit.byId('total').get('value') || dijit.byId('return_money').get('value') < 0){
			alert('invalid form');
			dijit.byId('recieve_money').focus();
			return false;
		}*/
		showDialog();			
	//}
}
function showDialog() {		   
	dijit.byId("popup_dept").show();
}
function hideDialog() {		
	dijit.byId("popup_dept").hide();
	//dijit.byId('frm_add_tran').submit();
}
var url_add_dept= '<?php echo $this->url(array('module'=>'global','controller'=>'index','action'=>'add-department')); ?>';
function addNewDepartmen(){
	if(dijit.byId('frm_add_dept').validate()) { 
		dojo.xhrPost({
		    url: url_add_dept,
		    form: dojo.byId('frm_add_dept'),
		    content : { 
			    'dept_name':dijit.byId('dpt_name').get('value'),
			    'shortcut':dijit.byId('shortcut').get('value'),
			    'status':dijit.byId('status').get('value'),			    
			},				    
		   handleAs:"json", 
		   load: function(response) {
		   hideDialog();
		   //sender  = getDataStorefromJSON('id','name', response);
		  // sender_store = sender;//assign for overived var sender_store
		   // dijit.byId('sender_name').set('store', sender_store);				    					    		    	
		    },
		    error: function(err) {
		    	 alert('<?php echo $tr->translate('INSERT_FAIL');?>');
		    }
		});
		}
}
</script>



