<?php 
	$servername ='localhost';//$data['servername'];
	$dbuser = 'root';//$data['dbuser'];
	$dbpassword ='';//$data['dbpassword'];
	$dbname = 'db_loan';//$data['dbname'];

	backup_tables($servername,$dbuser,$dbpassword,$dbname);
/* backup the db OR just a table */
	function backup_tables($host,$user,$pass,$name,$tables = '*')
	{
	
		$link = mysql_connect($host,$user,$pass);
		mysql_select_db($name,$link);
	
		//get all of the tables
		if($tables == '*')
		{
			$tables = array();
			$result = mysql_query('SHOW TABLES');
			while($row = mysql_fetch_row($result))
			{
				$tables[] = $row[0];
			}
		}
		else
		{
			$tables = is_array($tables) ? $tables : explode(',',$tables);
		}
	
		//cycle through
		foreach($tables as $table)
		{
			$result = mysql_query('SELECT * FROM '.$table);
			$num_fields = mysql_num_fields($result);
	
			$return.= 'DROP TABLE '.$table.';';
			$row2 = mysql_fetch_row(mysql_query('SHOW CREATE TABLE '.$table));
			$return.= "\n\n".$row2[1].";\n\n";
	
			for ($i = 0; $i < $num_fields; $i++)
			{
				while($row = mysql_fetch_row($result))
				{
					$return.= 'INSERT INTO '.$table.' VALUES(';
					for($j=0; $j<$num_fields; $j++)
					{
						$row[$j] = addslashes($row[$j]);
						$row[$j] = ereg_replace("\n","\\n",$row[$j]);
						//$row[$j] = preg_replace("#\n#","\\n",$row[$j]);
									
								//ereg_replace("/.*\.(.*)$/","\\1",$imgfile);
								//preg_replace("/.*\.(.*)$/", "\\1", "foo.jpg")
									
								if (isset($row[$j])) {
								$return.= '"'.$row[$j].'"' ;
								} else { $return.= '""';
				}
					if ($j<($num_fields-1)) {
					$return.= ',';
			}
		}
		$return.= ");\n";
		}
	}
	$return.="\n\n\n";
	}
	
	//save file
	$sql_file = 'db_loan_'.date('Y-m-d h-i').'.sql';
	//header('Content-disposition: attachment; filename="'.basename('/cs2_5/public'.$sql_file).'"');
	
	$handle = fopen($sql_file,'w+');
	fwrite($handle,$return);
	fclose($handle);
	
	$url = $_SERVER['REQUEST_URI'];
	$new_url =  str_replace("add","backup",$url);
	$redirect = 'http://' . $_SERVER['HTTP_HOST'].$new_url;
	header("Location:$redirect");
	die();			
}
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require('dijit.form.Button');	
</script>