<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_TUTION_FEE')); 
	$payment_term = $this->payment_term;
?>	
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
</style>
<?php $frm_set_price = $this->frm_set_price;?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'add-feetuition')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("SCHOOL_TUITION_FEES");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" cellspacing="10" broder 1>
						<tr>
							<td colspan="4">&nbsp;</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEGREE");?></td>
							<td><?php echo $frm_set_price->getElement('degree');?></td>
							<td><?php echo $tr->translate("FACULTIES");?></td>
							<td><?php echo $frm_set_price->getElement('faculty');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("BATCH");?></td>
							<td><?php echo $frm_set_price->getElement('batch');?></td>
							<td><?php echo $tr->translate("CREATED_DATE");?></td>
							<td><?php echo $frm_set_price->getElement('create_date');?></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td colspan="2">
							</td>
						</tr>
					</table>
					<table class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%; background:#DFF7FD;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								 	<?php $id=0; for($i = 0;$i < count($payment_term);$i++){ ?>
									<?php $id++;if($i==0)$term = $id;
									else{$term.=','.$id;} ?>
								<?php }?>
									<input type="hidden" name="iden_term" id="iden_term"  value="<?php echo $term;?>" >
									<input type="hidden" name="identity" id="identity"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="center"></tr>
									</table>
								</td>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<td colspan="8" align="center">
									<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									 iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'accounting','controller'=>"fee",'action'=>'index'),null,true); ?>';" />
									<input type="submit" label="<?php echo $tr->translate('SAVE');?>" id="save_new" dojoType="dijit.form.Button" 
								 		iconClass="dijitEditorIcon dijitEditorIconSave"/>
								</td>
							</tr>
						</tfoot>
				 </table>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
function printSave(){		
}
function CheckDegree(){
	id = dijit.byId("degree").value;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	no=0;
	if(id==2){ 
		dijit.byId("faculty").set('disabled',false);
		//dijit.byId("lbl_titlemetion").html("ddd");
		dojo.byId("lbl_titlemetion").innerHTML = "<?php echo $tr->translate("MENTION");?>";
		//temp+='<th id="lbl_titlemetion"></th>';
		ResetRecordRecord();
		addRow();
		/*$("#lbl_titlemetion").show();
		for(var n = 0; n < rowIDArray.length; n++) {
			$("#lbl_metion"+rowIDArray[n]).show();
		}	
		var metion = '<?php //echo $this->all_faculty; ?>';*/
	}
	else{
		dojo.byId("lbl_titlemetion").innerHTML = "<?php echo $tr->translate("FACULTIES");?>";
		dijit.byId("faculty").set('disabled',true);
		ResetRecordRecord();
		addRow();
		}
}
function ResetRecordRecord() {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays.length==1){
		deleteRecord(identity);
	}	
	else{
		for(var i=0;i<arrays.length;i++) {
			deleteRecord(arrays[i]);
		}
	}
}
var template = '';
var faculty = '<?php echo $this->all_faculty; ?>';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
//var pay_term ="<?php //print_r($payment_term);?>";

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("FACULTIES");?></th>';
			<?php $s=0; ?>
			<?php foreach ($payment_term as $value){?>
			<?php echo"temp+='<th>$value</th>';"; ?>
			<?php }?>
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="6%" align="center">'+no+'</td>';
			id = dijit.byId("degree").value;
			if(id!=2){
			template+='<td align="center" id="lbl_metion'+col+'"><select class="full" dojoType="dijit.form.FilteringSelect" name="metion'+col+'" id="metion'+col+'" >'+faculty+'</select></td>';
			}else{
				template+='<td align="center" id="lbl_metion'+col+'"><select class="full" dojoType="dijit.form.FilteringSelect" name="metion'+col+'" id="metion'+col+'" >'+metion+'</select></td>';
			}
			column = 0;
			for(j=0;j<payment_term;j++){ column++;
				template+='<td width="9%"><input type="text" required="true" id="fee'+col+'_'+column+'" name="fee'+col+'_'+column+'" dojoType="dijit.form.NumberTextBox" style="width: 100%;" /></td>';
			}
			template+='<td class="quater-input"><input type="text" required="true" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"style="width: 100%;"/><label id="subsub"></label></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
dojo.ready(function(){
	var metion = '<?php echo $this->all_metion; ?>';
	checkDegree();
	 addRow();
	 
});
function checkDegree(){
	id = dijit.byId("degree").value;
	if(id!=2){
		dijit.byId("faculty").set('disabled',true);
	} 
}
 function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>