<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SRMS_TEACHER"));
?>	
<?php $frm =  $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'services','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<div dojoType="dijit.layout.AccordionPane">
	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" onclick="showDialog();" showLabel="true" type="button"><?php echo $tr->translate("SEARCH");?></button>
	<input class="right"  type="button"​ id="add-room" Iconclass="dijitIconNewTask" value="<?php echo $tr->translate("ADD_NEW");?>" label="<?php echo $tr->translate("ADD_NEW");?>" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $this->url(array('module'=>'accounting','controller'=>"fee",'action'=>'add-feetuition'),null,true); ?>';"/>
</div>
<?php echo $this->list; ?>
</form>
<?php $frm_search = $this->frm_search;?>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" data-dojo-props="title:'<?php echo $tr->translate("SEARCH");?>', onCancel:hideDialog" id="popup_dept" >
		<form id='frm_add_dept' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table cellpadding="5" cellspacing="5">
			<tr>
				<td><?php echo $tr->translate("CODE");?></td>
				<td><?php echo $frm_search->getElement("fee_code");?></td>
				<td><?php echo $tr->translate("DEGREE");?></td>
				<td><?php echo $frm_search->getElement("degree");?></td>
			</tr>
			<tr>
				<td><?php echo $tr->translate("BATCH");?></td>
				<td><?php echo $frm_search->getElement("batch");?></td>
				<td><?php echo $tr->translate("FACULTIES");?></td>
				<td><?php echo $frm_search->getElement("faculty");?></td>
			</tr>
			<tr>
				<td><?php echo $tr->translate("MENTION");?></td>
				<td><?php echo $frm_search->getElement("metion");?></td>
				<td><?php echo $tr->translate("STATUS");?></td>
				<td><?php echo $frm_search->getElement("status_search");?></td>
			</tr>
			<tr>
				<td colspan="4" align="center"><br />
					<input type="submit"  label="<?php echo $tr->translate("SEARCH");?>" id="submitButton" 
					dojoType="dijit.form.Button" iconClass="dijitIconSearch" />
			</tr>
			
		</table>
		</form>
	</div>
</div>
 <script type="text/javascript">
function showDialog() {	
	dijit.byId("popup_dept").show();
}
function hideDialog() {		
	dijit.byId("popup_dept").hide();
}
 </script>
 