<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS_STUDENT_REQUEST'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<style>
select{ width:100%;}
fieldset{  background:none;}
</style>
<?php $register = $this->frm_request;?>
<form id='frm_stu_payment' action="<?php echo $this->url(array('module'=>'transfer','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
	    <fieldset style="background:#DFF7FD;">
		 <legend align="center"><strong><?php echo $tr->translate("STUDENT_REQUEST_FORM");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" padding:10px;" cellspacing="7">
						<tr>
							<td style="width: 150px"></td>
							<td></td>
							<td ><?php echo $tr->translate("RECEIPT_NO")."<sup>o</sup>";?></td>
							<td><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("YEAR");?></td>
							<td><?php echo $register->getElement('year');?></td>
							<td><?php echo $tr->translate("STUDENT_ID"); ?></td>
							<td><?php echo $register->getElement('stu_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("FACULTIES");?></td>
							<td><?php echo $register->getElement("dept");?></td>
							<td><?php echo $tr->translate("SESSION");?></td>
							<td><?php echo $register->getElement('session');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DOB");?></td>
							<td><?php echo $register->getElement('dob');?></td>
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><?php echo $register->getElement('phone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("POB");?></td>
							<td><?php echo $register->getElement('pob');?></td>
							<td><?php echo $tr->translate("CURRENT_ADD");?></td>
							<td><?php echo $register->getElement('current_add');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("REQUEST_FOR");?></td>
							<td><?php echo $register->getElement('request_id');?></td>
							<td><?php echo $tr->translate('REMARK');?></td>
							<td><?php echo $register->getElement('remark');?></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td><?php ?></td>
							<td><?php ?></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td><?php echo $tr->translate("PAID_DATE");?></td>
							<td><?php echo $register->getElement('pay_date');?></td>
						</tr>
						<tr>
						<tr>
							<td></td>
							<td></td>
							<td><?php echo $tr->translate("AMOUNT_PAID");?></td>
							<td><?php echo $register->getElement("payment_paid");?></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td colspan="2">
							<input type="button" value="<?php echo $tr->translate('SAVE');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId('frm_add_tran').submit();"/>
								<input type="button" value="Save & Print" label="Save & Print" id="busyButton" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>	
			</fieldset>	
		</td>
	</tr>
</table>	
</form>
<script>
function printSave(){		
	if(dijit.byId('frm_stu_payment').validate()) {
		/*if(dijit.byId('recieve_money').get('value') < dijit.byId('total').get('value') || dijit.byId('return_money').get('value') < 0){
			alert('សូម​ពិនិត្រ ទឹក​ដែល​​ទទួល​បាន​ម្តង ​ទៀត..');
			dijit.byId('recieve_money').focus();
			return false;
		}*/
		//showDialog();		
		dijit.byId("terms").show();	
	}
	
}
		//function showDialog() {		
		/*dojo.byId("lblinvioice").innerHTML = "ប័ណ្ណ​ផ្ទេរ​ប្រាក់";
		if(dijit.byId('tran_type').value == 1){
			dojo.byId("lblinvioice").innerHTML = "ប័ណ្ណ​ទទួល​ប្រាក់";
		}
		dojo.byId("lblsendername").innerHTML = dijit.byId("sender").value;		
		dojo.byId("lblrecievername").innerHTML = dijit.byId("reciever").value;
		dojo.byId("lblrecievertel").innerHTML = dijit.byId("reciever_tel").value;
		dojo.byId("lblrecieve_money").innerHTML = dojo.byId("gave").value + " " + dojo.byId('type_money').value;
		dojo.byId("lblcommission").innerHTML = dojo.byId("commission").value + " " + dojo.byId('type_money').value;
		dojo.byId("lbltotal").innerHTML = dojo.byId("total").value + " " + dojo.byId('type_money').value;
		var mkh = new Array('មករា', 'កុម្ភៈ', 'មីនា', 'មេសា', 'ឧសភា', 'មិថុនា', 'កក្កដា', 'សីហា', 'កញ្ញា', 'តុលា', 'វិច្ឆិកា', 'ធ្នូរ');
		var d = dojo.byId("epx_date").value.split('/');
		dojo.byId("lblexpdate").innerHTML = d[0] + " " + mkh[(d[1]-1)] +" "+d[2];

		var addr= dojo.byId('province').value.split(' ');
		
		var agentadd = addr[0];
		var agentname = dojo.byId('agent_id').value;
		var houseno = dijit.byId('agent_id').item.house_no;
		var streetno = dijit.byId('agent_id').item.street_no;
		var block = dijit.byId('agent_id').item.block;
		var agenttel = dijit.byId('agent_id').item.tel;
		if (dojo.byId('sub_agent_id').value !== '' ){			
			agentname = dojo.byId('sub_agent_id').value;
			houseno = dijit.byId('sub_agent_id').item.house_no;
			streetno = dijit.byId('sub_agent_id').item.street_no;
			block = dijit.byId('sub_agent_id').item.block;
			agenttel = dijit.byId('sub_agent_id').item.tel;
			agentadd = dijit.byId('sub_agent_id').item.province;
		}
		dojo.byId("lbladd").innerHTML = agentadd;		
		dojo.byId("lblstreetno").innerHTML = streetno;
		dojo.byId("lblhouseno").innerHTML = houseno;
		dojo.byId("lblblock").innerHTML = block;		
		dojo.byId("lblagentname").innerHTML = agentname;
		dojo.byId("lblagenttel").innerHTML = agenttel;
		    
		if(dijit.byId("tran_type").value == 1){
			dojo.byId("lblplacestatus").innerHTML = "<?php //echo $this->keycode['rpt-transfer-recieve-kh'];?>";
		}
		else{
			//dojo.byId("lblplacestatus").innerHTML = "<?php //echo $this->keycode['rpt-transfer-send-kh'];?>"; 	 	
		}   
		dijit.byId("terms").show();*/
	//}
     //dijit.byId("terms").show();
     
</script>
<div class="dijitHidden">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT");?>'" id="terms" >
		<div id="divPrint" style="width: 21cm; height: 14cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
			</style>	
			<table bgcolor="#DFF7FD" cellspacing="5" style="width: 21cm;height: 14cm; font-size:12pt; padding: 0px; margin: 0px;">
					<tr height="50px">
						<td><img src="<?php echo $base_url.'/images/logo.png';?>" width="50%"/></td>
					   	<td align="center" colspan="2">	
				            <strong style="font-size: 24px;font-weight:bold"><?php echo $keycode['branch'];?></strong><br/>
							<strong style="font-size: 20px;font-weight:bold"><?php echo $keycode['branch_en'];?></strong><br/>
			            </td>
			            <td></td>
				   </tr>
				   <tr height="50px">
						<td></td>
					   	<td align="center" colspan="2">	
				            <strong style="font-size: 22px;"><?php echo $keycode['request_student']; ?></strong><br/>
							<strong style="line-height:2px; font-size: 16px;"><?php echo $keycode['request_student_en'];?></strong>
			            </td>
			            <td>Receipt N<sup>o</sup> 062951</td>
				   </tr>
					<tr>
						<td width="25%">នាម - គោត្តនាម</td>
						<td  width="25%">&nbsp; : ជា ដានី</td>
						<td  width="25%">Full Name(First|Last):</td>
					   	<td  width="25%">&nbsp; : Chea Dany</td>
				   </tr>
				   <tr>
						<td>ID N<sup>o</sup></td>
						<td>&nbsp; : B8-008</td>
						<td>Year</td>
					   	<td>&nbsp; : 4</td>
				   </tr>
				    <tr>
						<td>Session</td>
						<td>&nbsp; : Everning</td>
						<td>Faculty</td>
						<td>&nbsp; : Business</td>
						
				   </tr>
				    <tr>
						<td>Date of Birth</td>
						<td>&nbsp; : 30/03/1990 </td>
						<td>Place of Birth</td>
						<td>&nbsp; : Phnom Penh</td>
				   </tr>
				   <tr>
						<td>Request for:</td>
						<td>&nbsp; : Certificate of Completion</td>
						<td>Other</td>
						<td>&nbsp; : Graduated</td>
				   </tr>
				   <tr>
						<td>&nbsp; :</td>
						<td>&nbsp; :</td>
						<td>Paid</td>
						<td>&nbsp; : 10 $</td>
				   </tr>
				   <tr>
						<td>ឈ្មោះអ្នកទទូល :</td>
						<td>&nbsp; : <?php $session_user=new Zend_Session_Namespace('auth');
			        			$username = $session_user->first_name; echo $username;?></td>
						<td>Paid Date</td>
						<td>&nbsp; : 23/02/2014</td>
				   </tr>
				   <tr>
						<td colspan="2">
						<hr size="1" />
							<?php $brachs = explode('/',$keycode['footer_branch']);?>
							<ul style="list-style-type: none;">
								<?php foreach ($brachs AS $key =>$branch):?>
								<li><?php echo $branch;?></li>
							    <?php endforeach;?>
							</ul>
						</td>
						<td>
						<hr size="1" />
							<?php $phones = explode('/',$keycode['foot_phone']);?>
							<ul style="list-style-type: none;">
								<?php foreach ($phones AS $key =>$phone):?>
								<li><?php echo $phone;?></li>
							    <?php endforeach;?>
							</ul>
						</td>
						<td>
						<hr size="1" />
							<?php $phones = explode('/',$keycode['foot_phone']);?>
							<ul style="list-style-type: none;">
								<?php foreach ($phones AS $key =>$phone):?>
								<li><?php echo $phone;?></li>
							    <?php endforeach;?>
							</ul>
						</td>			
				   </tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
	</div>
</div>