<?php 
$icon = 'dijitIconSave,
		dijitIconPrint,
		dijitIconCut,
		dijitIconCopy,
		dijitIconClear,
		dijitIconDelete,
		dijitIconUndo,
		dijitIconEdit,
		dijitIconNewTask,
		dijitIconEditTask,
		dijitIconEditProperty,
		dijitIconTask,
		dijitIconFilter,
		dijitIconConfigure,
		dijitIconSearch,
		dijitIconApplication,
		dijitIconBookmark,
		dijitIconChart,
		dijitIconConnector,
		dijitIconDatabase,
		dijitIconDocuments,
		dijitIconMail,
		dijitLeaf,
		dijitIconFile,
		dijitIconFunction,
		dijitIconKey,
		dijitIconPackage,
		dijitIconSample,
		dijitIconTable,
		dijitIconUsers,
		dijitFolderClosed,
		dijitIconFolderClosed,
		dijitFolderOpened,
		dijitIconFolderOpen,
		dijitIconError,

';
?>
<?php $array = explode(",", $icon);?>
<?php foreach ($array as $index =>$id){?>
<button id='<?php echo $index;?>' iconClass="<?php echo $array[$index]?>" dojoType="dijit.form.Button" title="<?php echo $array[$index]?>" ​onclick="showDialog();" showLabel="true" type="button" >បន្ថែម</button>​ 
<?php }?>
